$ find -name *image*.bb
./meta-fsl-demos/recipes-fsl/images/fsl-image-gui-sdk.bb
./meta-fsl-demos/recipes-fsl/images/fsl-image-test.bb
./meta-fsl-demos/recipes-fsl/images/fsl-image-gui.bb
./meta-fsl-demos/recipes-qt/images/qt-in-use-image.bb
./meta-fsl-demos/recipes-qt/images/qte-in-use-image.bb
./meta-openembedded/meta-initramfs/recipes-bsp/images/initramfs-kexecboot-klibc-image.bb
./meta-openembedded/meta-initramfs/recipes-bsp/images/initramfs-kexecboot-image.bb
./meta-openembedded/meta-oe/recipes-support/imagemagick/imagemagick_6.7.5.bb
./meta-openembedded/meta-oe/recipes-multimedia/libsdl-image/libsdl-image_1.2.12.bb
./poky/meta-hob/recipes-core/images/hob-image.bb
./poky/meta-skeleton/recipes-multilib/images/core-image-multilib-example.bb
./poky/meta/recipes-devtools/mkelfimage/mkelfimage_svn.bb
./poky/meta/recipes-sato/images/core-image-sato-dev.bb
./poky/meta/recipes-sato/images/core-image-sato.bb
./poky/meta/recipes-sato/images/core-image-sato-sdk.bb
./poky/meta/recipes-qt/images/qt4e-demo-image.bb
./poky/meta/recipes-core/images/core-image-minimal.bb
./poky/meta/recipes-core/images/core-image-base.bb
./poky/meta/recipes-core/images/core-image-minimal-dev.bb
./poky/meta/recipes-core/images/core-image-minimal-initramfs.bb
./poky/meta/recipes-core/images/build-appliance-image.bb
./poky/meta/recipes-core/images/core-image-minimal-mtdutils.bb
./poky/meta/recipes-extended/images/core-image-lsb-sdk.bb
./poky/meta/recipes-extended/images/core-image-basic.bb
./poky/meta/recipes-extended/images/core-image-lsb-dev.bb
./poky/meta/recipes-extended/images/core-image-lsb.bb
./poky/meta/recipes-graphics/images/core-image-directfb.bb
./poky/meta/recipes-graphics/images/core-image-x11.bb
./poky/meta/recipes-graphics/images/core-image-clutter.bb
./poky/meta/recipes-graphics/xcb/xcb-util-image_0.3.9.bb
./poky/meta/recipes-bsp/u-boot/u-boot-mkimage_2012.04.01.bb
./poky/meta/recipes-bsp/u-boot/u-boot-mkimage_2011.06.bb
./poky/meta/recipes-bsp/u-boot/u-boot-mkimage_2011.03.bb
./poky/meta/recipes-rt/images/core-image-rt-sdk.bb
./poky/meta/recipes-rt/images/core-image-rt.bb
