Statistics for meta-freescale
-----------------------------

Processed 424 csets from 26 developers
7 employers found
A total of 14966 lines added, 11026 removed (delta 3940)

Developers with the most changesets
Ting Liu                    83 (19.6%)
Otavio Salvador             80 (18.9%)
Fabio Berton                79 (18.6%)
Tom Hochstein               45 (10.6%)
Zhenhua Luo                 39 (9.2%)
Lauren Post                 36 (8.5%)
Yuqing Zhu                  13 (3.1%)
Daiane Angolini              8 (1.9%)
Zongchun Yu                  6 (1.4%)
Max Krummenacher             4 (0.9%)
Breno Lima                   4 (0.9%)
Chunrong Guo                 4 (0.9%)
Dominic Sacré               3 (0.7%)
Carlos Rafael Giani          3 (0.7%)
Andreas Müller              2 (0.5%)
Sona Sarmadi                 2 (0.5%)
Jun Zhu                      2 (0.5%)
Adrian Dudau                 2 (0.5%)
Cristian Stoica              2 (0.5%)
Mirza Krak                   1 (0.2%)
Richard Purdie               1 (0.2%)
Marco Franchi                1 (0.2%)
Stefan Agner                 1 (0.2%)
Camelia Groza                1 (0.2%)
Yuan Yao                     1 (0.2%)
Fabio Estevam                1 (0.2%)

Developers with the most changed lines
Cristian Stoica           7640 (39.8%)
Tom Hochstein             2662 (13.9%)
Lauren Post               2534 (13.2%)
Ting Liu                  2051 (10.7%)
Yuqing Zhu                1429 (7.5%)
Otavio Salvador           1185 (6.2%)
Zhenhua Luo                475 (2.5%)
Fabio Berton               254 (1.3%)
Sona Sarmadi               220 (1.1%)
Adrian Dudau               171 (0.9%)
Zongchun Yu                153 (0.8%)
Chunrong Guo                90 (0.5%)
Daiane Angolini             88 (0.5%)
Max Krummenacher            76 (0.4%)
Dominic Sacré              45 (0.2%)
Jun Zhu                     38 (0.2%)
Richard Purdie              11 (0.1%)
Marco Franchi               10 (0.1%)
Camelia Groza               10 (0.1%)
Carlos Rafael Giani          9 (0.0%)
Andreas Müller              8 (0.0%)
Yuan Yao                     8 (0.0%)
Breno Lima                   4 (0.0%)
Stefan Agner                 4 (0.0%)
Fabio Estevam                2 (0.0%)
Mirza Krak                   1 (0.0%)

Developers with the most lines removed
Ting Liu                   667 (6.0%)
Cristian Stoica            422 (3.8%)
Otavio Salvador             75 (0.7%)
Max Krummenacher            47 (0.4%)
Camelia Groza                7 (0.1%)
Carlos Rafael Giani          3 (0.0%)

Developers with the most signoffs (total 345)
Otavio Salvador            308 (89.3%)
Ting Liu                    23 (6.7%)
Sujith Haridasan             3 (0.9%)
Tom Hochstein                2 (0.6%)
Marian Chereji               1 (0.3%)
Xufeng Zhang                 1 (0.3%)
Yashpal Dutta                1 (0.3%)
Sujith H                     1 (0.3%)
Noor                         1 (0.3%)
Abdur Rehman                 1 (0.3%)
Prabhu Sundararaj            1 (0.3%)
Jun Zhu                      1 (0.3%)
Zhenhua Luo                  1 (0.3%)

Developers with the most reviews (total 1)
Horia Ioan Geanta Neag       1 (100.0%)

Developers with the most test credits (total 0)

Developers who gave the most tested-by credits (total 0)

Developers with the most report credits (total 2)
Tom Hochstein                1 (50.0%)
Jun Zhu                      1 (50.0%)

Developers who gave the most report credits (total 2)
Otavio Salvador              1 (50.0%)
Richard Purdie               1 (50.0%)

Top changeset contributors by employer
NXP                        239 (56.4%)
O.S. Systems               159 (37.5%)
(Unknown)                   13 (3.1%)
Freescale                    7 (1.7%)
ENEA AB                      4 (0.9%)
Toradex                      1 (0.2%)
Linux Foundation             1 (0.2%)

Top lines changed by employer
NXP                       16795 (87.6%)
O.S. Systems              1439 (7.5%)
Freescale                  399 (2.1%)
ENEA AB                    391 (2.0%)
(Unknown)                  139 (0.7%)
Linux Foundation            11 (0.1%)
Toradex                      4 (0.0%)

Employers with the most signoffs (total 345)
O.S. Systems               308 (89.3%)
NXP                         27 (7.8%)
Mentor Graphics              5 (1.4%)
Freescale                    3 (0.9%)
(Unknown)                    1 (0.3%)
Wind River                   1 (0.3%)

Employers with the most hackers (total 27)
NXP                         13 (48.1%)
(Unknown)                    5 (18.5%)
Freescale                    3 (11.1%)
O.S. Systems                 2 (7.4%)
ENEA AB                      2 (7.4%)
Linux Foundation             1 (3.7%)
Toradex                      1 (3.7%)


Statistics for meta-freescale-3rdparty
--------------------------------------

Processed 60 csets from 11 developers
6 employers found
A total of 3206 lines added, 9180 removed (delta -5974)

Developers with the most changesets
Fabio Berton                18 (30.0%)
Ian Coolidge                 9 (15.0%)
Max Krummenacher             9 (15.0%)
Daiane Angolini              8 (13.3%)
Andreas Müller              4 (6.7%)
Akshay Bhat                  4 (6.7%)
Otavio Salvador              3 (5.0%)
Dominic Sacré               2 (3.3%)
Amin Bandali                 1 (1.7%)
Stefan Agner                 1 (1.7%)
Breno Lima                   1 (1.7%)

Developers with the most changed lines
Akshay Bhat               6950 (58.7%)
Fabio Berton              3087 (26.1%)
Max Krummenacher           804 (6.8%)
Daiane Angolini            502 (4.2%)
Dominic Sacré             269 (2.3%)
Andreas Müller             83 (0.7%)
Ian Coolidge                68 (0.6%)
Otavio Salvador             67 (0.6%)
Stefan Agner                 5 (0.0%)
Breno Lima                   3 (0.0%)
Amin Bandali                 1 (0.0%)

Developers with the most lines removed
Akshay Bhat               5091 (55.5%)
Fabio Berton              2413 (26.3%)

Developers with the most signoffs (total 57)
Otavio Salvador             57 (100.0%)

Developers with the most reviews (total 0)

Developers with the most test credits (total 1)
Daiane Angolini              1 (100.0%)

Developers who gave the most tested-by credits (total 1)
Fabio Berton                 1 (100.0%)

Developers with the most report credits (total 0)

Developers who gave the most report credits (total 0)

Top changeset contributors by employer
O.S. Systems                21 (35.0%)
(Unknown)                   16 (26.7%)
NXP                          9 (15.0%)
Boundary Devices             9 (15.0%)
Timesys                      4 (6.7%)
Toradex                      1 (1.7%)

Top lines changed by employer
Timesys                   6950 (58.7%)
O.S. Systems              3154 (26.6%)
(Unknown)                 1157 (9.8%)
NXP                        505 (4.3%)
Boundary Devices            68 (0.6%)
Toradex                      5 (0.0%)

Employers with the most signoffs (total 57)
O.S. Systems                57 (100.0%)

Employers with the most hackers (total 11)
(Unknown)                    4 (36.4%)
O.S. Systems                 2 (18.2%)
NXP                          2 (18.2%)
Timesys                      1 (9.1%)
Boundary Devices             1 (9.1%)
Toradex                      1 (9.1%)


Statistics for meta-freescale-distro
------------------------------------

Processed 36 csets from 6 developers
2 employers found
A total of 568 lines added, 373 removed (delta 195)

Developers with the most changesets
Otavio Salvador             15 (41.7%)
Fabio Berton                11 (30.6%)
Tom Hochstein                5 (13.9%)
Lauren Post                  2 (5.6%)
Yuqing Zhu                   2 (5.6%)
Jun Zhu                      1 (2.8%)

Developers with the most changed lines
Fabio Berton               249 (31.2%)
Otavio Salvador            239 (30.0%)
Lauren Post                231 (29.0%)
Tom Hochstein               42 (5.3%)
Yuqing Zhu                  34 (4.3%)
Jun Zhu                      2 (0.3%)

Developers with the most lines removed
Lauren Post                180 (48.3%)

Developers with the most signoffs (total 22)
Otavio Salvador             21 (95.5%)
Fabio Berton                 1 (4.5%)

Developers with the most reviews (total 0)

Developers with the most test credits (total 0)

Developers who gave the most tested-by credits (total 0)

Developers with the most report credits (total 0)

Developers who gave the most report credits (total 0)

Top changeset contributors by employer
O.S. Systems                26 (72.2%)
NXP                         10 (27.8%)

Top lines changed by employer
O.S. Systems               488 (61.2%)
NXP                        309 (38.8%)

Employers with the most signoffs (total 22)
O.S. Systems                22 (100.0%)

Employers with the most hackers (total 6)
NXP                          4 (66.7%)
O.S. Systems                 2 (33.3%)


Statistics for base
-------------------

Processed 9 csets from 3 developers
2 employers found
A total of 89 lines added, 87 removed (delta 2)

Developers with the most changesets
Fabio Berton                 6 (66.7%)
Tom Hochstein                2 (22.2%)
Otavio Salvador              1 (11.1%)

Developers with the most changed lines
Fabio Berton                58 (44.6%)
Tom Hochstein               53 (40.8%)
Otavio Salvador             19 (14.6%)

Developers with the most lines removed
Otavio Salvador              1 (1.1%)

Developers with the most signoffs (total 8)
Otavio Salvador              8 (100.0%)

Developers with the most reviews (total 0)

Developers with the most test credits (total 0)

Developers who gave the most tested-by credits (total 0)

Developers with the most report credits (total 0)

Developers who gave the most report credits (total 0)

Top changeset contributors by employer
O.S. Systems                 7 (77.8%)
NXP                          2 (22.2%)

Top lines changed by employer
O.S. Systems                77 (59.2%)
NXP                         53 (40.8%)

Employers with the most signoffs (total 8)
O.S. Systems                 8 (100.0%)

Employers with the most hackers (total 3)
O.S. Systems                 2 (66.7%)
NXP                          1 (33.3%)


Statistics for Documentation
----------------------------

Processed 17 csets from 3 developers
3 employers found
A total of 1803 lines added, 2255 removed (delta -452)

Developers with the most changesets
Fabio Berton                 7 (41.2%)
Daiane Angolini              6 (35.3%)
Thomas Thorne                4 (23.5%)

Developers with the most changed lines
Daiane Angolini           1416 (55.7%)
Fabio Berton              1004 (39.5%)
Thomas Thorne              121 (4.8%)

Developers with the most lines removed
Daiane Angolini            658 (29.2%)

Developers with the most signoffs (total 0)

Developers with the most reviews (total 0)

Developers with the most test credits (total 0)

Developers who gave the most tested-by credits (total 0)

Developers with the most report credits (total 0)

Developers who gave the most report credits (total 0)

Top changeset contributors by employer
O.S. Systems                 7 (41.2%)
NXP                          6 (35.3%)
(Unknown)                    4 (23.5%)

Top lines changed by employer
NXP                       1416 (55.7%)
O.S. Systems              1004 (39.5%)
(Unknown)                  121 (4.8%)

Employers with the most signoffs (total 0)

Employers with the most hackers (total 3)
NXP                          1 (33.3%)
O.S. Systems                 1 (33.3%)
(Unknown)                    1 (33.3%)


