Statistics for meta-fsl-arm
---------------------------

Processed 212 csets from 27 developers
10 employers found
A total of 10773 lines added, 14170 removed (delta -3397)

Developers with the most changesets
Otavio Salvador            106 (50.0%)
Lauren Post                 39 (18.4%)
Daiane Angolini             12 (5.7%)
Mario Domenech Goulart       8 (3.8%)
Andy Voltz                   6 (2.8%)
Carlos Rafael Giani          4 (1.9%)
Javier Viguera               4 (1.9%)
Rogerio Nunes                4 (1.9%)
Prabhu Sundararaj            3 (1.4%)
Anthony Felice               3 (1.4%)
John Weber                   3 (1.4%)
Jacob Kroon                  2 (0.9%)
Eric Nelson                  2 (0.9%)
Gary Thomas                  2 (0.9%)
Mahesh Mahadevan             2 (0.9%)
stefan                       1 (0.5%)
Trevor Woerner               1 (0.5%)
Ann Thornton                 1 (0.5%)
Alexandre Belloni            1 (0.5%)
David Nyström               1 (0.5%)
Andreas Henriksson           1 (0.5%)
Sébastien Taylor            1 (0.5%)
Stéphane Cerveau            1 (0.5%)
Dan McGregor                 1 (0.5%)
Mats Kärrman                1 (0.5%)
Lucas Dutra Nunes            1 (0.5%)
Christopher Larson           1 (0.5%)

Developers with the most changed lines
Otavio Salvador           9870 (42.0%)
Lauren Post               4226 (18.0%)
Daiane Angolini           3298 (14.0%)
Jacob Kroon                680 (2.9%)
Prabhu Sundararaj          281 (1.2%)
Andy Voltz                  89 (0.4%)
Mario Domenech Goulart      70 (0.3%)
Carlos Rafael Giani         43 (0.2%)
Javier Viguera              40 (0.2%)
Dan McGregor                32 (0.1%)
Rogerio Nunes               11 (0.0%)
Stéphane Cerveau           10 (0.0%)
Anthony Felice               8 (0.0%)
Gary Thomas                  4 (0.0%)
Alexandre Belloni            3 (0.0%)
John Weber                   2 (0.0%)
Eric Nelson                  2 (0.0%)
Mahesh Mahadevan             2 (0.0%)
Christopher Larson           2 (0.0%)
stefan                       1 (0.0%)
Trevor Woerner               1 (0.0%)
Ann Thornton                 1 (0.0%)
David Nyström               1 (0.0%)
Andreas Henriksson           1 (0.0%)
Mats Kärrman                1 (0.0%)
Lucas Dutra Nunes            1 (0.0%)

Developers with the most lines removed
Otavio Salvador           7837 (55.3%)
Andy Voltz                  70 (0.5%)

Developers with the most signoffs (total 59)
Otavio Salvador             48 (81.4%)
Lauren Post                  4 (6.8%)
Anthony Felice               2 (3.4%)
John Weber                   1 (1.7%)
Fabio Estevam                1 (1.7%)
H. Peter Anvin               1 (1.7%)
Michal Marek                 1 (1.7%)
Wang Shengjiu                1 (1.7%)

Developers with the most reviews (total 1)
Alexandre Belloni            1 (100.0%)

Developers with the most test credits (total 6)
John Weber                   2 (33.3%)
Gary Thomas                  2 (33.3%)
Eric Nelson                  1 (16.7%)
Daiane Angolini              1 (16.7%)

Developers who gave the most tested-by credits (total 6)
Otavio Salvador              6 (100.0%)

Developers with the most report credits (total 8)
Richard Purdie               2 (25.0%)
Fabio Estevam                1 (12.5%)
Ilya Smelykh                 1 (12.5%)
Tarek El-Sherbiny            1 (12.5%)
Fabio Labruna                1 (12.5%)
Alfonso Tamés               1 (12.5%)
Jānis Čoders               1 (12.5%)

Developers who gave the most report credits (total 8)
Otavio Salvador              8 (100.0%)

Top changeset contributors by employer
O.S. Systems               115 (54.2%)
Freescale                   60 (28.3%)
(Unknown)                   17 (8.0%)
Timesys                      9 (4.2%)
Digi International           4 (1.9%)
Boundary Devices             2 (0.9%)
(Consultant)                 2 (0.9%)
Endian Technologies          1 (0.5%)
Linaro                       1 (0.5%)
Free Electrons               1 (0.5%)

Top lines changed by employer
O.S. Systems              11784 (50.1%)
Freescale                 10800 (45.9%)
(Unknown)                  776 (3.3%)
Timesys                    103 (0.4%)
Digi International          40 (0.2%)
(Consultant)                 4 (0.0%)
Free Electrons               3 (0.0%)
Boundary Devices             2 (0.0%)
Endian Technologies          1 (0.0%)
Linaro                       1 (0.0%)

Employers with the most signoffs (total 59)
O.S. Systems                48 (81.4%)
Freescale                    6 (10.2%)
Timesys                      2 (3.4%)
(Unknown)                    1 (1.7%)
Novell                       1 (1.7%)
Intel                        1 (1.7%)

Employers with the most hackers (total 28)
(Unknown)                   11 (39.3%)
Freescale                    6 (21.4%)
O.S. Systems                 3 (10.7%)
Timesys                      2 (7.1%)
Digi International           1 (3.6%)
(Consultant)                 1 (3.6%)
Free Electrons               1 (3.6%)
Boundary Devices             1 (3.6%)
Endian Technologies          1 (3.6%)
Linaro                       1 (3.6%)


Statistics for meta-fsl-arm-extra
---------------------------------

Processed 88 csets from 16 developers
8 employers found
A total of 16099 lines added, 5796 removed (delta 10303)

Developers with the most changesets
Otavio Salvador             24 (27.3%)
Eric Nelson                 12 (13.6%)
Alexandre Belloni           10 (11.4%)
John Weber                  10 (11.4%)
Anthony Felice               9 (10.2%)
Mario Domenech Goulart       5 (5.7%)
Carlos Rafael Giani          4 (4.5%)
Philip Balister              4 (4.5%)
Gary Thomas                  2 (2.3%)
Pavel Kopylov                2 (2.3%)
Daiane Angolini              1 (1.1%)
Christopher Larson           1 (1.1%)
Patrick Keil                 1 (1.1%)
Andreas Henriksson           1 (1.1%)
Dan McGregor                 1 (1.1%)
Lucas Dutra Nunes            1 (1.1%)

Developers with the most changed lines
Otavio Salvador           12953 (59.6%)
Carlos Rafael Giani       1201 (5.5%)
Eric Nelson                677 (3.1%)
Anthony Felice             608 (2.8%)
John Weber                 373 (1.7%)
Alexandre Belloni          222 (1.0%)
Mario Domenech Goulart      33 (0.2%)
Philip Balister              9 (0.0%)
Daiane Angolini              9 (0.0%)
Gary Thomas                  8 (0.0%)
Lucas Dutra Nunes            6 (0.0%)
Pavel Kopylov                4 (0.0%)
Dan McGregor                 4 (0.0%)
Christopher Larson           2 (0.0%)
Patrick Keil                 2 (0.0%)
Andreas Henriksson           1 (0.0%)

Developers with the most lines removed
Mario Domenech Goulart      13 (0.2%)

Developers with the most signoffs (total 13)
Otavio Salvador             12 (92.3%)
John Weber                   1 (7.7%)

Developers with the most reviews (total 0)

Developers with the most test credits (total 1)
Eric Nelson                  1 (100.0%)

Developers who gave the most tested-by credits (total 1)
Otavio Salvador              1 (100.0%)

Developers with the most report credits (total 3)
Gary Thomas                  1 (33.3%)
Diego                        1 (33.3%)
Omar Pighi                   1 (33.3%)

Developers who gave the most report credits (total 3)
Eric Nelson                  2 (66.7%)
Otavio Salvador              1 (33.3%)

Top changeset contributors by employer
O.S. Systems                30 (34.1%)
(Unknown)                   23 (26.1%)
Boundary Devices            12 (13.6%)
Free Electrons              10 (11.4%)
Timesys                      9 (10.2%)
(Consultant)                 2 (2.3%)
Freescale                    1 (1.1%)
Endian Technologies          1 (1.1%)

Top lines changed by employer
O.S. Systems              18594 (85.6%)
(Unknown)                 1595 (7.3%)
Boundary Devices           682 (3.1%)
Timesys                    608 (2.8%)
Free Electrons             237 (1.1%)
Freescale                    9 (0.0%)
(Consultant)                 8 (0.0%)
Endian Technologies          1 (0.0%)

Employers with the most signoffs (total 13)
O.S. Systems                12 (92.3%)
(Unknown)                    1 (7.7%)

Employers with the most hackers (total 16)
(Unknown)                    7 (43.8%)
O.S. Systems                 3 (18.8%)
Boundary Devices             1 (6.2%)
Timesys                      1 (6.2%)
Free Electrons               1 (6.2%)
Freescale                    1 (6.2%)
(Consultant)                 1 (6.2%)
Endian Technologies          1 (6.2%)


Statistics for meta-fsl-demos
-----------------------------

Processed 22 csets from 6 developers
4 employers found
A total of 389 lines added, 757 removed (delta -368)

Developers with the most changesets
Rogerio Nunes               10 (45.5%)
Mario Domenech Goulart       5 (22.7%)
Otavio Salvador              4 (18.2%)
Evan Kotara                  1 (4.5%)
John Weber                   1 (4.5%)
Eric Nelson                  1 (4.5%)

Developers with the most changed lines
Rogerio Nunes              606 (57.0%)
Otavio Salvador            145 (13.6%)
Mario Domenech Goulart      68 (6.4%)
Evan Kotara                 40 (3.8%)
John Weber                  25 (2.4%)
Eric Nelson                  1 (0.1%)

Developers with the most lines removed
Rogerio Nunes              363 (48.0%)
Otavio Salvador            133 (17.6%)

Developers with the most signoffs (total 2)
Rogerio Nunes                1 (50.0%)
Otavio Salvador              1 (50.0%)

Developers with the most reviews (total 0)

Developers with the most test credits (total 0)

Developers who gave the most tested-by credits (total 0)

Developers with the most report credits (total 0)

Developers who gave the most report credits (total 0)

Top changeset contributors by employer
Freescale                   11 (50.0%)
O.S. Systems                 9 (40.9%)
Boundary Devices             1 (4.5%)
(Unknown)                    1 (4.5%)

Top lines changed by employer
Freescale                  813 (76.5%)
O.S. Systems               224 (21.1%)
(Unknown)                   25 (2.4%)
Boundary Devices             1 (0.1%)

Employers with the most signoffs (total 2)
Freescale                    1 (50.0%)
O.S. Systems                 1 (50.0%)

Employers with the most hackers (total 6)
Freescale                    2 (33.3%)
O.S. Systems                 2 (33.3%)
(Unknown)                    1 (16.7%)
Boundary Devices             1 (16.7%)


Statistics for base
-------------------

Processed 10 csets from 6 developers
5 employers found
A total of 30 lines added, 66 removed (delta -36)

Developers with the most changesets
Trevor Woerner               4 (40.0%)
Otavio Salvador              2 (20.0%)
Mario Domenech Goulart       1 (10.0%)
Alexandre Belloni            1 (10.0%)
Timur Aydin                  1 (10.0%)
Daiane Angolini              1 (10.0%)

Developers with the most changed lines
Daiane Angolini             46 (59.7%)
Trevor Woerner              12 (15.6%)
Otavio Salvador              9 (11.7%)
Alexandre Belloni            3 (3.9%)
Mario Domenech Goulart       1 (1.3%)
Timur Aydin                  1 (1.3%)

Developers with the most lines removed
Daiane Angolini             42 (63.6%)

Developers with the most signoffs (total 6)
Otavio Salvador              6 (100.0%)

Developers with the most reviews (total 0)

Developers with the most test credits (total 0)

Developers who gave the most tested-by credits (total 0)

Developers with the most report credits (total 0)

Developers who gave the most report credits (total 0)

Top changeset contributors by employer
Linaro                       4 (40.0%)
O.S. Systems                 3 (30.0%)
Freescale                    1 (10.0%)
Free Electrons               1 (10.0%)
(Unknown)                    1 (10.0%)

Top lines changed by employer
Freescale                   46 (59.7%)
Linaro                      14 (18.2%)
O.S. Systems                13 (16.9%)
Free Electrons               3 (3.9%)
(Unknown)                    1 (1.3%)

Employers with the most signoffs (total 6)
O.S. Systems                 6 (100.0%)

Employers with the most hackers (total 6)
O.S. Systems                 2 (33.3%)
Freescale                    1 (16.7%)
Linaro                       1 (16.7%)
Free Electrons               1 (16.7%)
(Unknown)                    1 (16.7%)


Statistics for Documentation
----------------------------

Processed 43 csets from 6 developers
4 employers found
A total of 3970 lines added, 843 removed (delta 3127)

Developers with the most changesets
Mario Domenech Goulart      18 (41.9%)
Daiane Angolini             13 (30.2%)
Leonardo Sandoval            5 (11.6%)
Otavio Salvador              3 (7.0%)
Anthony Felice               3 (7.0%)
Carlos Rafael Giani          1 (2.3%)

Developers with the most changed lines
Leonardo Sandoval         1872 (45.0%)
Mario Domenech Goulart    1736 (41.7%)
Daiane Angolini            320 (7.7%)
Otavio Salvador             18 (0.4%)
Anthony Felice              17 (0.4%)
Carlos Rafael Giani          7 (0.2%)

Developers with the most lines removed

Developers with the most signoffs (total 4)
Otavio Salvador              2 (50.0%)
Mario Domenech Goulart       1 (25.0%)
Leonardo Sandoval            1 (25.0%)

Developers with the most reviews (total 0)

Developers with the most test credits (total 0)

Developers who gave the most tested-by credits (total 0)

Developers with the most report credits (total 0)

Developers who gave the most report credits (total 0)

Top changeset contributors by employer
O.S. Systems                21 (48.8%)
Freescale                   17 (39.5%)
Timesys                      3 (7.0%)
(Unknown)                    2 (4.7%)

Top lines changed by employer
O.S. Systems              1853 (44.5%)
Freescale                 1532 (36.8%)
(Unknown)                  758 (18.2%)
Timesys                     17 (0.4%)

Employers with the most signoffs (total 4)
O.S. Systems                 3 (75.0%)
(Unknown)                    1 (25.0%)

Employers with the most hackers (total 7)
O.S. Systems                 2 (28.6%)
(Unknown)                    2 (28.6%)
Freescale                    2 (28.6%)
Timesys                      1 (14.3%)


