Statistics for meta-fsl-arm
---------------------------

Processed 196 csets from 29 developers
11 employers found
A total of 7437 lines added, 4506 removed (delta 2931)

Developers with the most changesets
Otavio Salvador             66 (33.7%)
Chunrong Guo                21 (10.7%)
Carlos Rafael Giani         15 (7.7%)
Lauren Post                 11 (5.6%)
Neena Busireddy             10 (5.1%)
Jacob Kroon                  9 (4.6%)
Zhenhua Luo                  8 (4.1%)
Fabio Estevam                7 (3.6%)
Javier Viguera               6 (3.1%)
Max Krummenacher             5 (2.6%)
Alexander Shashkevych        5 (2.6%)
Daiane Angolini              5 (2.6%)
Wang Zidan                   4 (2.0%)
Gary Bisson                  3 (1.5%)
Nikolay Dimitrov             2 (1.0%)
Alexandre Belloni            2 (1.0%)
Mario Domenech Goulart       2 (1.0%)
Tony Felice                  2 (1.0%)
Eric Nelson                  2 (1.0%)
Alexey Ignatov               2 (1.0%)
Samuli Piippo                1 (0.5%)
Andreas Müller              1 (0.5%)
Gary Thomas                  1 (0.5%)
Christopher Larson           1 (0.5%)
Khem Raj                     1 (0.5%)
Jun Zhu                      1 (0.5%)
Thomas Elste                 1 (0.5%)
Thomas Senyk                 1 (0.5%)
Maciej Borzecki              1 (0.5%)

Developers with the most changed lines
Otavio Salvador           3920 (34.0%)
Zhenhua Luo               3201 (27.8%)
Gary Bisson               2182 (18.9%)
Christopher Larson         400 (3.5%)
Neena Busireddy            380 (3.3%)
Nikolay Dimitrov           363 (3.1%)
Chunrong Guo               239 (2.1%)
Carlos Rafael Giani        160 (1.4%)
Lauren Post                144 (1.2%)
Eric Nelson                115 (1.0%)
Wang Zidan                 103 (0.9%)
Max Krummenacher            62 (0.5%)
Khem Raj                    50 (0.4%)
Tony Felice                 39 (0.3%)
Jacob Kroon                 36 (0.3%)
Alexander Shashkevych       36 (0.3%)
Javier Viguera              35 (0.3%)
Daiane Angolini             19 (0.2%)
Mario Domenech Goulart      13 (0.1%)
Fabio Estevam                9 (0.1%)
Alexey Ignatov               8 (0.1%)
Alexandre Belloni            4 (0.0%)
Jun Zhu                      4 (0.0%)
Thomas Senyk                 4 (0.0%)
Gary Thomas                  3 (0.0%)
Samuli Piippo                1 (0.0%)
Thomas Elste                 1 (0.0%)
Maciej Borzecki              1 (0.0%)

Developers with the most lines removed
Gary Bisson               1975 (43.8%)
Lauren Post                 36 (0.8%)
Tony Felice                 33 (0.7%)
Javier Viguera              12 (0.3%)
Alexander Shashkevych        8 (0.2%)
Otavio Salvador              5 (0.1%)
Thomas Senyk                 3 (0.1%)
Gary Thomas                  3 (0.1%)

Developers with the most signoffs (total 131)
Otavio Salvador            130 (99.2%)
Richard Purdie               1 (0.8%)

Developers with the most reviews (total 0)

Developers with the most test credits (total 1)
Daiane Angolini              1 (100.0%)

Developers who gave the most tested-by credits (total 1)
Fabio Estevam                1 (100.0%)

Developers with the most report credits (total 5)
Petr Kubizňák              3 (60.0%)
Alexandre Belloni            2 (40.0%)

Developers who gave the most report credits (total 5)
Otavio Salvador              5 (100.0%)

Top changeset contributors by employer
O.S. Systems                68 (34.7%)
Freescale                   66 (33.7%)
(Unknown)                   46 (23.5%)
Digi International           6 (3.1%)
Boundary Devices             2 (1.0%)
Free Electrons               2 (1.0%)
Timesys                      2 (1.0%)
Pelagicore AB                1 (0.5%)
Mentor Graphics              1 (0.5%)
(None)                       1 (0.5%)
(Consultant)                 1 (0.5%)

Top lines changed by employer
Freescale                 4097 (35.5%)
O.S. Systems              3933 (34.1%)
(Unknown)                 2852 (24.7%)
Mentor Graphics            400 (3.5%)
Boundary Devices           115 (1.0%)
(None)                      50 (0.4%)
Timesys                     39 (0.3%)
Digi International          35 (0.3%)
Free Electrons               4 (0.0%)
Pelagicore AB                4 (0.0%)
(Consultant)                 3 (0.0%)

Employers with the most signoffs (total 131)
O.S. Systems               130 (99.2%)
Linux Foundation             1 (0.8%)

Employers with the most hackers (total 30)
(Unknown)                   12 (40.0%)
Freescale                    8 (26.7%)
O.S. Systems                 2 (6.7%)
Mentor Graphics              1 (3.3%)
Boundary Devices             1 (3.3%)
(None)                       1 (3.3%)
Timesys                      1 (3.3%)
Digi International           1 (3.3%)
Free Electrons               1 (3.3%)
Pelagicore AB                1 (3.3%)
(Consultant)                 1 (3.3%)


Statistics for meta-fsl-arm-extra
---------------------------------

Processed 77 csets from 16 developers
6 employers found
A total of 3969 lines added, 28686 removed (delta -24717)

Developers with the most changesets
Eric Nelson                 25 (32.5%)
Alex de Cabo                12 (15.6%)
John Weber                   7 (9.1%)
Otavio Salvador              6 (7.8%)
Christoph Settgast           6 (7.8%)
Daiane Angolini              4 (5.2%)
Ian Coolidge                 3 (3.9%)
Fabio Estevam                2 (2.6%)
Alfonso Tamés               2 (2.6%)
Raphael Silva                2 (2.6%)
Carlos Rafael Giani          2 (2.6%)
Rabeeh Khoury                2 (2.6%)
Nikolay Dimitrov             1 (1.3%)
Simon Kuhnle                 1 (1.3%)
Jacob Kroon                  1 (1.3%)
Gary Thomas                  1 (1.3%)

Developers with the most changed lines
Alex de Cabo              19956 (66.2%)
Carlos Rafael Giani       5811 (19.3%)
John Weber                3171 (10.5%)
Raphael Silva              704 (2.3%)
Rabeeh Khoury              279 (0.9%)
Eric Nelson                121 (0.4%)
Otavio Salvador             42 (0.1%)
Christoph Settgast          37 (0.1%)
Daiane Angolini             24 (0.1%)
Alfonso Tamés               7 (0.0%)
Ian Coolidge                 5 (0.0%)
Fabio Estevam                3 (0.0%)
Simon Kuhnle                 2 (0.0%)
Nikolay Dimitrov             1 (0.0%)
Jacob Kroon                  1 (0.0%)
Gary Thomas                  1 (0.0%)

Developers with the most lines removed
Alex de Cabo              19026 (66.3%)
Carlos Rafael Giani       3486 (12.2%)
John Weber                2748 (9.6%)
Rabeeh Khoury              273 (1.0%)
Christoph Settgast           7 (0.0%)
Fabio Estevam                2 (0.0%)
Ian Coolidge                 1 (0.0%)

Developers with the most signoffs (total 71)
Otavio Salvador             71 (100.0%)

Developers with the most reviews (total 2)
Eric Nelson                  2 (100.0%)

Developers with the most test credits (total 2)
Eric Nelson                  2 (100.0%)

Developers who gave the most tested-by credits (total 2)
Christoph Settgast           1 (50.0%)
Simon Kuhnle                 1 (50.0%)

Developers with the most report credits (total 0)

Developers who gave the most report credits (total 0)

Top changeset contributors by employer
Boundary Devices            28 (36.4%)
(Unknown)                   23 (29.9%)
Congatec AG                 12 (15.6%)
O.S. Systems                 8 (10.4%)
Freescale                    5 (6.5%)
(Consultant)                 1 (1.3%)

Top lines changed by employer
Congatec AG               19956 (66.2%)
(Unknown)                 9326 (30.9%)
O.S. Systems               746 (2.5%)
Boundary Devices           126 (0.4%)
Freescale                   10 (0.0%)
(Consultant)                 1 (0.0%)

Employers with the most signoffs (total 71)
O.S. Systems                71 (100.0%)

Employers with the most hackers (total 17)
(Unknown)                    9 (52.9%)
O.S. Systems                 2 (11.8%)
Boundary Devices             2 (11.8%)
Freescale                    2 (11.8%)
Congatec AG                  1 (5.9%)
(Consultant)                 1 (5.9%)


Statistics for meta-fsl-demos
-----------------------------

Processed 21 csets from 9 developers
5 employers found
A total of 256 lines added, 62 removed (delta 194)

Developers with the most changesets
Otavio Salvador              8 (38.1%)
Daiane Angolini              5 (23.8%)
Neena Busireddy              2 (9.5%)
Max Krummenacher             1 (4.8%)
Matt Madison                 1 (4.8%)
Alexander Shashkevych        1 (4.8%)
Alex Gonzalez                1 (4.8%)
Trevor Woerner               1 (4.8%)
Carlos Rafael Giani          1 (4.8%)

Developers with the most changed lines
Carlos Rafael Giani        157 (60.6%)
Daiane Angolini             48 (18.5%)
Otavio Salvador             34 (13.1%)
Neena Busireddy             10 (3.9%)
Max Krummenacher             4 (1.5%)
Alexander Shashkevych        3 (1.2%)
Matt Madison                 1 (0.4%)
Alex Gonzalez                1 (0.4%)
Trevor Woerner               1 (0.4%)

Developers with the most lines removed
Max Krummenacher             1 (1.6%)
Alexander Shashkevych        1 (1.6%)

Developers with the most signoffs (total 13)
Otavio Salvador             13 (100.0%)

Developers with the most reviews (total 0)

Developers with the most test credits (total 0)

Developers who gave the most tested-by credits (total 0)

Developers with the most report credits (total 0)

Developers who gave the most report credits (total 0)

Top changeset contributors by employer
O.S. Systems                 8 (38.1%)
Freescale                    6 (28.6%)
(Unknown)                    5 (23.8%)
Digi International           1 (4.8%)
Linaro                       1 (4.8%)

Top lines changed by employer
(Unknown)                  183 (70.7%)
Freescale                   40 (15.4%)
O.S. Systems                34 (13.1%)
Digi International           1 (0.4%)
Linaro                       1 (0.4%)

Employers with the most signoffs (total 13)
O.S. Systems                13 (100.0%)

Employers with the most hackers (total 10)
(Unknown)                    5 (50.0%)
Freescale                    2 (20.0%)
O.S. Systems                 1 (10.0%)
Digi International           1 (10.0%)
Linaro                       1 (10.0%)


Statistics for base
-------------------

Processed 5 csets from 4 developers
4 employers found
A total of 40 lines added, 29 removed (delta 11)

Developers with the most changesets
Trevor Woerner               2 (40.0%)
John Weber                   1 (20.0%)
Otavio Salvador              1 (20.0%)
Ting Liu                     1 (20.0%)

Developers with the most changed lines
Trevor Woerner              34 (49.3%)
Otavio Salvador             29 (42.0%)
Ting Liu                     5 (7.2%)
John Weber                   1 (1.4%)

Developers with the most lines removed
Otavio Salvador             29 (100.0%)

Developers with the most signoffs (total 4)
Otavio Salvador              4 (100.0%)

Developers with the most reviews (total 0)

Developers with the most test credits (total 0)

Developers who gave the most tested-by credits (total 0)

Developers with the most report credits (total 0)

Developers who gave the most report credits (total 0)

Top changeset contributors by employer
Linaro                       2 (40.0%)
Freescale                    1 (20.0%)
O.S. Systems                 1 (20.0%)
(Unknown)                    1 (20.0%)

Top lines changed by employer
Linaro                      34 (49.3%)
O.S. Systems                29 (42.0%)
Freescale                    5 (7.2%)
(Unknown)                    1 (1.4%)

Employers with the most signoffs (total 4)
O.S. Systems                 4 (100.0%)

Employers with the most hackers (total 4)
O.S. Systems                 1 (25.0%)
Linaro                       1 (25.0%)
Freescale                    1 (25.0%)
(Unknown)                    1 (25.0%)


Statistics for Documentation
----------------------------

Processed 94 csets from 5 developers
3 employers found
A total of 4080 lines added, 2775 removed (delta 1305)

Developers with the most changesets
Daiane Angolini             52 (55.3%)
Lucas Dutra Nunes           20 (21.3%)
Mario Domenech Goulart      11 (11.7%)
Otavio Salvador              6 (6.4%)
Bob Cochran                  5 (5.3%)

Developers with the most changed lines
Daiane Angolini           3410 (80.2%)
Lucas Dutra Nunes          443 (10.4%)
Bob Cochran                214 (5.0%)
Mario Domenech Goulart     105 (2.5%)
Otavio Salvador             78 (1.8%)

Developers with the most lines removed

Developers with the most signoffs (total 16)
Daiane Angolini              8 (50.0%)
Otavio Salvador              6 (37.5%)
Lucas Dutra Nunes            2 (12.5%)

Developers with the most reviews (total 0)

Developers with the most test credits (total 1)
Daiane Angolini              1 (100.0%)

Developers who gave the most tested-by credits (total 1)
Daiane Angolini              1 (100.0%)

Developers with the most report credits (total 0)

Developers who gave the most report credits (total 0)

Top changeset contributors by employer
Freescale                   39 (41.5%)
O.S. Systems                37 (39.4%)
(Unknown)                   18 (19.1%)

Top lines changed by employer
Freescale                 2232 (52.5%)
(Unknown)                 1392 (32.8%)
O.S. Systems               626 (14.7%)

Employers with the most signoffs (total 16)
Freescale                    8 (50.0%)
O.S. Systems                 8 (50.0%)

Employers with the most hackers (total 6)
O.S. Systems                 3 (50.0%)
(Unknown)                    2 (33.3%)
Freescale                    1 (16.7%)


