======================  ======================   ====================
Board                   barebox Provider         barebox Version
======================  ======================   ====================
cfa10036                barebox                  |barebox_mainline_version|
cfa10037                barebox                  |barebox_mainline_version|
cfa10049                barebox                  |barebox_mainline_version|
cfa10055                barebox                  |barebox_mainline_version|
cfa10056                barebox                  |barebox_mainline_version|
cfa10057                barebox                  |barebox_mainline_version|
cfa10058                barebox                  |barebox_mainline_version|
======================  ======================   ====================

