========  ================  ===============
Board     Barebox Provider  Barebox Version
========  ================  ===============
cfa10036  barebox           2013.08.0      
cfa10037  barebox           2013.08.0      
cfa10049  barebox           2013.08.0      
cfa10055  barebox           2013.08.0      
cfa10056  barebox           2013.08.0      
cfa10057  barebox           2013.08.0      
cfa10058  barebox           2013.08.0      
========  ================  ===============
