======  ==========  ========================================================================================================================
Bug ID  Resolution                                                          Summary
======  ==========  ========================================================================================================================
10287   INVALID     gst-play is broken
10602   FIXED       meta-freescale layer inclusion breaks other machines
11139   NOTABUG     Locale settings does not have effects
11153   NOTABUG     Generated locales does not support UTF-8 encoding
5098    WONTFIX     gpu-viv-bin-mx6q-3.5.7-1.0.0-alpha.2-sfp.bin and gpu-viv-bin-mx6q-3.5.7-1.0.0-alpha.2-hfp.bin are missing OpenGL headers
6690    FIXED       qemu fails during configuration task
6703    FIXED       Kernel hangs on boot when HDMI cable is plugged
======  ==========  ========================================================================================================================
