======  ==========  =======================================================================================
Bug ID  Resolution  Summary
======  ==========  =======================================================================================
4511    WONTFIX     error for using oprofile.ko to profiling
5023    FIXED       EXTRA_IMAGE_FEATURES += "tools-sdk" does return ERROR
5148    WONTFIX     perf test fails
5178    WORKSFORME  sabresd boot failure with preferred provider linux-fslc
5219    FIXED       meta-fsl-arm kernel crash when using graphics acceleration
5361    FIXED       resolvconf fail to change dns-nameservers from /etc/network/interfaces
5826    FIXED       ARM: recipe xserver-xorg-2_1.15.0-r0: task do_compile: Failed
5864    FIXED       .bbappend files with % in their name and "python __anonymous () { ... }" fails to parse
6083    FIXED       Vivante GPU doesn't work with X11
6098    FIXED       u-boot-fslc-v2014.01-r0: task do_compile: Failed
6545    FIXED       weston patches applied unconditionally
6894    WONTFIX     kernel menuconfig unusable and errors during compileing
7226    WORKSFORME  bitbake failure - MACHINE=cubox-i PACKAGE_CLASSES=package_deb
7384    FIXED       u-boot-fslc fails in master
======  ==========  =======================================================================================
