======  ==========  =======================================================================================
Bug ID  Resolution  Summary
======  ==========  =======================================================================================
3719    WORKSFORME  fsl-image-gui image for imx6qsabreauto machine does not reboot
4510    WONTFIX     GLX load vivante_dri.so failed
4511    WONTFIX     error for using oprofile.ko to profiling
5023    FIXED       EXTRA_IMAGE_FEATURES += "tools-sdk" does return ERROR
5148    WONTFIX     perf test fails
5178    WORKSFORME  sabresd boot failure with preferred provider linux-fslc
5202    NOTABUG     distorted images from gstreamer
5219    FIXED       meta-fsl-arm kernel crash when using graphics acceleration
5359    FIXED       [Yocto 1.5] su - USER -c 'COMMAND' env variable issue
5361    FIXED       resolvconf fail to change dns-nameservers from /etc/network/interfaces
5607    OBSOLETE    MCIMX-LVDS1 trhows unknown mouse event on Qt 4.8
5826    FIXED       ARM: recipe xserver-xorg-2_1.15.0-r0: task do_compile: Failed
5864    FIXED       .bbappend files with % in their name and "python __anonymous () { ... }" fails to parse
6083    FIXED       Vivante GPU doesn't work with X11
6098    FIXED       u-boot-fslc-v2014.01-r0: task do_compile: Failed
6545    FIXED       weston patches applied unconditionally
6703    FIXED       Kernel hangs on boot when HDMI cable is plugged
6894    WONTFIX     kernel menuconfig unusable and errors during compileing
7226    WORKSFORME  bitbake failure - MACHINE=cubox-i PACKAGE_CLASSES=package_deb
7384    FIXED       u-boot-fslc fails in master
7799    FIXED       Parse failure due to gstreamer 0.10 removal
7811    FIXED       Buffer corruption after resizing wayland client
7845    INVALID     bitbake fsl-image-qt5 build error for board VAR-SOM-MX6
7998    WORKSFORME  qt-x11-free (meta-qt3) has host contamination
8266    FIXED       meta-fsl-arm fails do_compile of xf86-video-imxfb-vivante
8287    FIXED       meta-fsl* fails on perf install
8737    WORKSFORME  xf86-video-imxfb-vivante build fails for imx6qsabresd on autobuilder
8802    FIXED       meta-fsl-* fails in universe fetch
8898    FIXED       meta-fsl-arm has unconditional bbappends for qt4
8945    FIXED       meta-fsl-arm layer fails to parse with MACHINE = "imx28evk
======  ==========  =======================================================================================
