* **linux-boundary**: Linux kernel for Boundary Devices boards.
* **linux-cfa**: Linux kernel for Crystalfontz boards.
* **linux-congatec**: linux-congatec version 3.10.17-r0.
* **linux-cubox-i**: Linux kernel that is based on Linaro's 3.14 releases, with full support for the i.MX6 features.
* **linux-denx**: DENX mainline based Linux kernel.
* **linux-fslc**: Linux kernel based on mainline kernel used by FSL Community BSP in order to provide support for some backported features and fixes, or because it was applied in linux-next and takes some time to become part of a stable version, or because it is not applicable for upstreaming.
* **linux-imx**: Linux Kernel provided and supported by Freescale with focus on i.MX Family Reference Boards. It includes support for many IPs such as GPU, VPU and IPU.
* **linux-ls1**: Linux Kernel provided and supported by Freescale with focus on Layerscape1 Family Boards. 
* **linux-timesys**: Linux Kernel with added drivers and board support for Vybrid-based platforms.
* **linux-wandboard**: Linux kernel for Wandboard.
