=========================     =====================================   ===============
Package Name                  Package version (BSP from Freescale)    HW
=========================     =====================================   ===============
imx-test                      |latest_bsp_version_mx6|                HW related
imx-lib                       |latest_bsp_version_mx6|                HW related
imx-kobs                      |latest_bsp_version_mx6|                HW related
firmware-imx                  |latest_bsp_version_mx6|                HW related
gpu-viv-bin-mx6q              |latest_bsp_version_mx6|                HW acceleration
gpu-viv-g2d                   |latest_bsp_version_mx6|                HW related
xf86-dri-vivante              |latest_bsp_version_mx6|                HW acceleration
xf86-video-imxfb-vivante      |latest_bsp_version_mx6|                HW acceleration
gst-fsl-plugin                |mm_version|                            HW related
libfslcodec                   |mm_version|                            HW acceleration
libfslparser                  |mm_version|                            HW optimization
libfslvpuwrap                 |libfslvpuwrap_version|                 HW related
fsl-alsa-plugins              1.0.25                                  HW related
=========================     =====================================   ===============
