================      =====================================    ================
Package Name          Package version (BSP from Freescale)     HW
================      =====================================    ================
gst-fsl-plugin        |mm_version|                             HW optimization
imx-test              2.6.35.3-1.1.0                           HW related
libfslcodec           |mm_version|                             HW optimization
libfslparser          |mm_version|                             HW optimization
================      =====================================    ================
