* **u-boot-boundary**: U-Boot for Boundary Devices boards
* **u-boot-congatec**: u-boot which includes support for Congatec Boards.
* **u-boot-fslc**: U-Boot based on mainline U-Boot used by FSL Community BSP in order to provide support for some backported features and fixes, or because it was submitted for revision and it takes some time to become part of a stable version, or because it is not applicable for upstreaming.
* **u-boot-imx**: i.MX U-Boot suppporting i.MX reference boards.
* **u-boot-kontron**: U-Boot for Kontron based boards.
* **u-boot-qoriq**: U-Boot provided by Freescale with focus on QorIQ boards
* **u-boot-toradex**: U-Boot bootloader with support for Toradex Computer on Modules.
* **u-boot-variscite**: U-Boot for Variscite i.MX6Q/DL VAR-SOM-MX6.
