* **linux-boundary**: Linux kernel for Boundary Devices boards.
* **linux-cfa**: Linux kernel for Crystalfontz boards.
* **linux-compulab**: Linux kernel for CompuLab cm-fx6 boards.
* **linux-congatec**: linux-congatec version 3.14-r0.
* **linux-cubox-i**: Linux kernel that is based on Linaro's 3.14 releases, with full support for the i.MX6 features.
* **linux-denx**: DENX mainline based Linux kernel.
* **linux-fslc**: Linux kernel based on mainline kernel used by FSL Community BSP in order to provide support for some backported features and fixes, or because it was applied in linux-next and takes some time to become part of a stable version, or because it is not applicable for upstreaming.
* **linux-fslc-mx6**: Linux kernel based on Freescale 3.14.28 GA release, used by FSL Community BSP in order to provide support for i.MX6 based platforms and include official Linux kernel stable updates, backported features and fixes coming from the vendors, kernel community or FSL Community itself.
* **linux-gateworks-imx**: linux-gateworks-imx version 3.14-r0.
* **linux-imx**: Linux Kernel provided and supported by Freescale with focus on i.MX Family Reference Boards. It includes support for many IPs such as GPU, VPU and IPU.
* **linux-ls1**: Linux Kernel provided and supported by Freescale with focus on Layerscape1 Family Boards. 
* **linux-timesys**: Linux Kernel with added drivers and board support for Vybrid-based platforms.
* **linux-toradex**: Linux kernel for Toradex Colibri VFxx Computer on Modules.
* **linux-wandboard**: Linux kernel for Wandboard.
