* **barebox**: Barebox - a bootloader that inherits the best of U-Boot and the Linux kernel
* **u-boot-boundary**: Universal Boot Loader for embedded devices.
* **u-boot-congatec**: Universal Boot Loader for embedded devices.
* **u-boot-cubox-i**: Universal Boot Loader for embedded devices.
* **u-boot-fslc**: U-boot bootloader for Freescale ARM platforms
* **u-boot-imx**: bootloader for imx platforms
* **u-boot-ls1**: Universal Boot Loader for embedded devices.
* **u-boot-timesys**: bootloader for Vybrid platforms
