========================     =====================================   ================
Package Name                 Package version (BSP from Freescale)     HW
========================     =====================================   ================
amd-gpu-x11-bin-mx51         11.09.01                                HW acceleration
firmware-imx                 3.0.35-4.0.0                            HW-specific
gst-fsl-plugin               |mm_version|                            HW-specific
imx-lib                      11.09.02                                HW-specific
imx-test                     11.09.01                                HW-specific
imx-vpu                      11.09.02                                HW acceleration
libfslcodec                  |mm_version|                            HW acceleration
libfslparser                 |mm_version|                            HW optimization
libz160                      11.09.01                                HW-specific
xf86-video-imxfb             11.09.01                                HW acceleration
========================     =====================================   ================
