========================     =====================================   ================
Package Name                 Package version (BSP from Freescale)     HW
========================     =====================================   ================
imx-test                     11.09.01                                HW related
imx-lib                      11.09.01                                HW related
firmware-imx                 11.09.01                                HW related
amd-gpu-x11-bin-mx51         11.09.01                                HW acceleration
xf86-video-imxfb             11.09.01                                HW acceleration
libfslparser                 3.0.7                                   HW optimization
gst-fsl-plugin               3.0.7                                   HW optimization
libfslcodec                  3.0.7                                   HW optimization
========================     =====================================   ================
