================      =====================================    ================
Package Name          Package version (BSP from Freescale)     HW
================      =====================================    ================
imx-test              2.6.35.3-1.1.0                           HW related
libfslparser          3.0.7                                    HW optimization
gst-fsl-plugin        3.0.7                                    HW optimization
libfslcodec           3.0.7                                    HW optimization
================      =====================================    ================
