=========================     =====================================   ===============
Package Name                  Package version (BSP from Freescale)    HW
=========================     =====================================   ===============
imx-test                      1.1.0                                   HW related
imx-lib                       1.1.0                                   HW related
firmware-imx                  1.1.0                                   HW related
gpu-viv-bin-mx6q              1.1.0                                   HW acceleration
xf86-dri-vivante              1.1.0                                   HW acceleration
xf86-video-imxfb-vivante      1.1.0                                   HW acceleration
gst-fsl-plugin                3.0.7                                   HW related
libfslcodec                   3.0.7                                   HW acceleration
libfslparser                  3.0.7                                   HW optimization
libfslvpuwrap                 1.0.35                                  HW related
=========================     =====================================   ===============
