========================     =====================================   ================
Package Name                 Package version (BSP from Freescale)     HW
========================     =====================================   ================
imx-test                     11.09.01                                HW related
imx-lib                      11.09.01                                HW related
firmware-imx                 11.09.01                                HW related
amd-gpu-x11-bin-mx51         11.09.01                                HW acceleration
xf86-video-imxfb             11.09.01                                HW acceleration
gst-fsl-plugin               2.0.3                                   HW related
fsl-mm-codeclib              2.0.3                                   HW acceleration
fsl-mm-flv-codeclib          2.0.3                                   HW optimization
fsl-mm-mp3enc-codeclib       2.0.3                                   HW optimization
========================     =====================================   ================
