* **barebox**: Barebox - a bootloader that inherits the best of U-Boot and the Linux kernel
* **u-boot-boundary**: u-boot for Boundary Devices boards.
* **u-boot-fslc**: U-Boot based on mainline U-Boot used by FSL Community BSP in order to provide support for some backported features and fixes, or because it was submitted for revision and it takes some time to become part of a stable version, or because it is not applicable for upstreaming.
* **u-boot-imx**: U-Boot provided by Freescale with focus on  i.MX reference boards.
* **u-boot-karo**: u-boot for Ka-Ro electronics TX Computer-On-Modules.
* **u-boot-qoriq**: U-Boot provided by Freescale with focus on QorIQ boards
* **u-boot-toradex**: U-Boot bootloader with support for Toradex Computer on Modules.
* **u-boot-variscite**: U-Boot for Variscite i.MX6Q/DL VAR-SOM-MX6.
