* **linux-advantech**: linux-advantech version ${LINUX_VERSION}+gitAUTOINC+6ea635c2f9-r0.
* **linux-boundary**: Linux kernel for Boundary Devices boards.
* **linux-congatec**: linux-congatec version 4.9.11+gitAUTOINC+da3c7d59e1-r0.
* **linux-fslc**: Linux kernel based on mainline kernel used by FSL Community BSP in order to provide support for some backported features and fixes, or because it was applied in linux-next and takes some time to become part of a stable version, or because it is not applicable for upstreaming.
* **linux-fslc-imx**: Linux Kernel provided by NXP as the part of release distribution. Main focus is set on i.MX Family Reference Boards. It includes support for many NXP Proprietary IPs (GPU, VPU, IPU). Latest stable Kernel patchlevel is applied and maintained by Community.
* **linux-fslc-qoriq**: Linux kernel based on LTS kernel used by FSL Community BSP in order to provide support for some backported features and fixes, or because it was applied in linux-next and takes some time to become part of a stable version, or because it is not applicable for upstreaming.
* **linux-gateworks-imx**: linux-gateworks-imx version ${LINUX_VERSION}+gitAUTOINC+d9991ca465-r0.
* **linux-kontron**: Kontron Linux mainline based kernel with backported features and fixes.
* **linux-qoriq**: Linux Kernel for NXP QorIQ platforms.
* **linux-toradex**: Linux kernel for Toradex Freescale i.MX based modules.
* **linux-variscite**: linux-variscite version 4.14.78+gitAUTOINC+0b8118cd4d-r0.
