+------------------+---------------------------------+-----------------------------+
|                  | |freescale_release_name|        | |project_name|              |
+==================+=================================+=============================+
|**Intended use**  |Reference system for BSP modules |Reference system for use as  |
|                  |test and validation on Freescale |base for any project for all |
|                  |Reference Boards                 |supported boards             |
+------------------+---------------------------------+-----------------------------+
|**Code**          |Static. Only include any bug     |Updates. Receives bug fixes  |
|                  |fixes on the upcoming release    |and has security issues      |
|                  |                                 |fixed often                  |
+------------------+---------------------------------+-----------------------------+
|**Contribution**  |Indirect contribution via        |Open, everyone is welcome to |
|                  ||project_name|. After revision,  |contribute to the project    |
|                  |contribution may be merged in    |                             |
|                  |upcoming release                 |                             |
+------------------+---------------------------------+-----------------------------+
|**Board Support** |Limited, as it supports just the |Extended, as it supports both|
|                  |Freescale evaluation boards      |Freescale evaluation boards  |
|                  |listed in the Release Notes      |and 3rd party boards.        |
|                  |                                 |See :ref:`supported-boards`  |
+------------------+---------------------------------+-----------------------------+
|**Yocto Project** |No                               |Yes                          |
|**Compatible**    |                                 |                             |
+------------------+---------------------------------+-----------------------------+
|**Support**       |i.MX Community                   |meta-freescale               |
+------------------+---------------------------------+-----------------------------+
|**Repository**    |git.freescale.com                |github.com/Freescale         |
+------------------+---------------------------------+-----------------------------+

