========================     =====================================
Package Name                 Package version (BSP from Freescale)
========================     =====================================
imx-test                     11.09.01
imx-lib                      11.09.01
firmware-imx                 11.09.01
amd-gpu-x11-bin-mx51         11.09.01
xf86-video-imxfb             11.09.01 
gst-fsl-plugin               2.0.3
fsl-mm-codeclib              2.0.3
fsl-mm-flv-codeclib          2.0.3
fsl-mm-mp3enc-codeclib       2.0.3
========================     =====================================
