=========================  ==================================================
         Machine             Basic Feature List                              
=========================  ==================================================
cgtqmx6                    
imx233-olinuxino-maxi      
imx233-olinuxino-micro     
imx233-olinuxino-mini      
imx23evk                   
imx28evk                   
imx31pdk                   
imx35pdk                   
imx51evk                   
imx53ard                   
imx53qsb                   
imx6dlsabresd              
imx6qsabreauto             
imx6qsabrelite             
imx6qsabresd               
imx6slevk                  
nitrogen6x                 
wandboard-dual             
wandboard-solo             
=========================  ==================================================
