===============   ======================
Board             Kernel Verion_FSL BSP
===============   ======================
imx28evk          2.6.35_maintain
imx51evk          2.6.35_maintain
imx53qsb          2.6.35_maintain
imx53ard          2.6.35_maintain
imx6dlsabresd     3.0.35_4.0.0
imx6qsabreauto    3.0.35_4.0.0
imx6qsabresd      3.0.35_4.0.0
imx6slevk         3.0.35_4.0.0
===============   ======================

