======================  =============================
       Machine                       Name
======================  =============================
imx233-olinuxino-maxi   OLIMEX iMX233-OLinuXino-Maxi
imx233-olinuxino-micro  OLIMEX iMX233-OLinuXino-Micro
imx233-olinuxino-mini   OLIMEX iMX233-OLinuXino-Mini
imx233-olinuxino-nano   OLIMEX iMX233-OLinuXino-Nano
lx2160acex7             Solid-Run LX2160A-CEx7
======================  =============================
