=========================  ==================================================  ==========  ==========
         Machine             Name                                                 SoC        Layer
=========================  ==================================================  ==========  ==========
cgtqmx6                    Congatec Qmx6                                                   meta-fsl-arm-extra
imx23evk                   Freescale i.MX23 Evaluation Kit                     i.MX23      meta-fsl-arm
imx28evk                   Freescale i.MX28 Evaluation Kit                     i.MX28      meta-fsl-arm
imx31pdk                   Freescale i.MX31 Platform Development Kit           i.MX31      meta-fsl-arm
imx35pdk                   Freescale i.MX35 Platform Development Kit           i.MX35      meta-fsl-arm
imx51evk                   Freescale i.MX51 Evaluation Kit                     i.MX51      meta-fsl-arm
imx53qsb                   Freescale i.MX53 Quick Start Board                  i.MX53      meta-fsl-arm
imx53ard                   Freescale i.MX53 SABRE Automotive Board             i.MX53      meta-fsl-arm
imx6dlsabresd              Freescale i.MX6DL SABRE Smart Device                i.MX6DL     meta-fsl-arm
imx6qsabreauto             Freescale i.MX6Q SABRE Automotive                   i.MX6Q      meta-fsl-arm
imx6qsabresd               Freescale i.MX6Q SABRE Smart Device                 i.MX6Q      meta-fsl-arm
imx6slevk                  Freescale i.MX6SL Evaluation Kit                    i.MX6SL     meta-fsl-arm
imx233-olinuxino-maxi      iMX233-OLinuXino-Maxi                                           meta-fsl-arm-extra
imx233-olinuxino-micro     iMX233-OLinuXino-Micro                                          meta-fsl-arm-extra
imx233-olinuxino-mini      iMX233-OLinuXino-Mini                                           meta-fsl-arm-extra
imx6qsabrelite             i.MX6Q SABRE Lite                                               meta-fsl-arm-extra
wandboard-dual             i.MX6 Wandboard Dual                                            meta-fsl-arm-extra
wandboard-solo             i.MX6 Wandboard Solo                                            meta-fsl-arm-extra
nitrogen6x                 Nitrogen6X                                                      meta-fsl-arm-extra
=========================  ==================================================  ==========  ==========
