================  ========================================
Machine           Name
================  ========================================
apalis-imx6       Toradex Apalis iMX6Q/D
cfa10036          Crystalfontz CFA-10036
cfa10037          Crystalfontz CFA-10037
cfa10049          Crystalfontz CFA-10049
cfa10055          Crystalfontz CFA-10055
cfa10056          Crystalfontz CFA-10056
cfa10057          Crystalfontz CFA-10057
cfa10058          Crystalfontz CFA-10058
cgtqmx6           Congatec QMX6 Evaluation board
cm-fx6            CompuLab CM-FX6
colibri-imx6      Toradex Colibri iMX6DL/S
colibri-vf        Toradex Colibri VF50/VF61
cubox-i           SolidRun CuBox-i and HummingBoard
imx23evk          Freescale i.MX23 Evaluation Kit
imx28evk          Freescale i.MX28 Evaluation Kit
imx51evk          Freescale i.MX51 Evaluation Kit
imx53ard          Freescale i.MX53 SABRE Automotive Board
imx53qsb          Freescale i.MX53 Quick Start Board
imx6dl-riotboard  RIoTboard
imx6dlsabreauto   Freescale i.MX6DL SABRE Automotive
imx6dlsabresd     Freescale i.MX6DL SABRE Smart Device
imx6qpsabreauto   Freescale i.MX6Q Plus SABRE Automotive
imx6qpsabresd     Freescale i.MX6Q Plus SABRE Smart Device
imx6qsabreauto    Freescale i.MX6Q SABRE Automotive
imx6qsabrelite    Boundary Devices i.MX6Q SABRE Lite
imx6qsabresd      Freescale i.MX6Q SABRE Smart Device
imx6sl-warp       WaRP
imx6slevk         Freescale i.MX6SL Evaluation Kit
imx6solosabresd   Freescale i.MX6Solo SABRE Smart Device
imx6sxsabreauto   Freescale i.MX6SoloX Sabre Automotive
imx6sxsabresd     Freescale i.MX6SoloX SabreSD
imx6ulevk         Freescale i.MX6UL Evaluation Kit
imx7dsabresd      Freescale i.MX7D SABRE Smart Device
ls1021atwr        Freescale LS1021ATWR board
nitrogen6sx       Boundary Devices Nitrogen6SX
nitrogen6x        Boundary Devices Nitrogen6X
nitrogen6x-lite   Boundary Devices Nitrogen6X Lite
pcm052            Phytec phyCORE Vybrid Development Kit
twr-vf65gs10      Freescale Vybrid TWR-VF65GS10
ventana           i.MX6Q/DL Ventana Platform
wandboard         Wandboard i.MX6 Wandboard Quad/Dual/Solo
================  ========================================
