=====================  ==================================================
       Machine                                Name
=====================  ==================================================
apalis-imx6            Toradex Apalis iMX6Q/D
b4420qds               Freescale B4420QDS
b4420qds-64b           Freescale B4420QDS-64B
b4860qds               Freescale B4860QDS
b4860qds-64b           Freescale B4860QDS-64B
c293pcie               Freescale C293PCIE
cfa10036               Crystalfontz CFA-10036
cfa10037               Crystalfontz CFA-10037
cfa10049               Crystalfontz CFA-10049
cfa10055               Crystalfontz CFA-10055
cfa10056               Crystalfontz CFA-10056
cfa10057               Crystalfontz CFA-10057
cfa10058               Crystalfontz CFA-10058
cgtqmx6                Congatec QMX6 Evaluation board
cm-fx6                 CompuLab CM-FX6
colibri-imx6           Toradex Colibri iMX6DL/S
colibri-imx7           Toradex Colibri iMX7D/S
colibri-vf             Toradex Colibri VF50/VF61
cubox-i                SolidRun CuBox-i and HummingBoard
imx23evk               Freescale i.MX23 Evaluation Kit
imx28evk               Freescale i.MX28 Evaluation Kit
imx51evk               Freescale i.MX51 Evaluation Kit
imx53ard               Freescale i.MX53 SABRE Automotive Board
imx53qsb               Freescale i.MX53 Quick Start Board
imx6dl-riotboard       RIoTboard
imx6dlsabreauto        Freescale i.MX6DL SABRE Automotive
imx6dlsabresd          Freescale i.MX6DL SABRE Smart Device
imx6q-dms-ba16         Advantech DMS BA16
imx6qdl-variscite-som  Variscite i.MX6Q/DL VAR-SOM-MX6
imx6qpsabreauto        Freescale i.MX6Q Plus SABRE Automotive
imx6qpsabresd          Freescale i.MX6Q Plus SABRE Smart Device
imx6qsabreauto         Freescale i.MX6Q SABRE Automotive
imx6qsabrelite         Boundary Devices i.MX6Q SABRE Lite
imx6qsabresd           Freescale i.MX6Q SABRE Smart Device
imx6sl-warp            WaRP
imx6slevk              Freescale i.MX6SL Evaluation Kit
imx6solosabresd        Freescale i.MX6Solo SABRE Smart Device
imx6sxsabreauto        Freescale i.MX6SoloX Sabre Automotive
imx6sxsabresd          Freescale i.MX6SoloX SabreSD
imx6ul-pico-hobbit     Hobbitboard (PICO-IMX6UL)
imx6ulevk              Freescale i.MX6UL Evaluation Kit
imx7dsabresd           Freescale i.MX7D SABRE Smart Device
imx7s-warp             WaRP7
ls1021atwr             Freescale LS1021ATWR board
ls1043ardb             NXP LS1043ARDB board
ls1043ardb-32b         NXP LS1043ARDB-32B
ls1046ardb             NXP LS1046ARDB
ls2080ardb             NXP LS2080ARDB board
nitrogen6sx            Boundary Devices Nitrogen6SX
nitrogen6x             Boundary Devices Nitrogen6X
nitrogen6x-lite        Boundary Devices Nitrogen6X Lite
nitrogen7              Boundary Devices Nitrogen7
p2041rdb               Freescale P2041RDB
p3041ds                Freescale P3041DS
p4080ds                Freescale P4080DS
p5020ds                Freescale P5020DS
p5020ds-64b            Freescale P5020DS-64B
p5040ds                Freescale P5040DS
p5040ds-64b            Freescale P5040DS-64B
pcm052                 Phytec phyCORE Vybrid Development Kit
t1023rdb               Freescale T1023RDB
t1024rdb-64b           Freescale T1024RDB
t1040d4rdb             Freescale T1040D4RDB
t1042d4rdb-64b         Freescale T1042D4RDB
t2080qds               Freescale T2080QDS
t2080qds-64b           Freescale T2080QDS-64B
t2080rdb               Freescale T2080RDB
t4160qds               Freescale T4160QDS
t4160qds-64b           Freescale T4160QDS-64B
t4240qds               Freescale T4240QDS
t4240qds-64b           Freescale T4240QDS-64B
t4240rdb               Freescale T4240RDB
twr-vf65gs10           Freescale Vybrid TWR-VF65GS10
tx6q-11x0              Ka-Ro electronics i.MX6Q TX6Q Computer-On-Module
tx6s-8035              Ka-Ro electronics i.MX6S TX6S Computer-On-Module
tx6u-8033              Ka-Ro electronics i.MX6DL TX6DL Computer-On-Module
ventana                i.MX6Q/DL Ventana Platform
wandboard              Wandboard i.MX6 Wandboard Quad/Dual/Solo
=====================  ==================================================
