======================  =========================================
Machine                 Name
======================  =========================================
imx233-olinuxino-maxi   OLIMEX iMX233-OLinuXino-Maxi
imx233-olinuxino-micro  OLIMEX iMX233-OLinuXino-Micro
imx233-olinuxino-mini   OLIMEX iMX233-OLinuXino-Mini
imx233-olinuxino-nano   OLIMEX iMX233-OLinuXino-Nano
imx31pdk                Freescale i.MX31 Platform Development Kit
imx35pdk                Freescale i.MX35 Platform Development Kit
imx6solosabreauto       Freescale i.MX6Solo SABRE Automotive
m28evk                  DENX M28 SoM Evaluation Kit
m53evk                  DENX M53 SoM Evaluation Kit
======================  =========================================
