======================  =================================================  =======================  =======================
       Machine                                 Name                                  SoC                     Layer
======================  =================================================  =======================  =======================
apalis-imx6             Toradex Apalis iMX6Q/D                             i.MX6Q                   meta-freescale-3rdparty
colibri-imx6            Toradex Colibri iMX6DL/S                           i.MX6DL                  meta-freescale-3rdparty
colibri-imx6ull         Toradex Colibri iMX6ULL                            i.MX6ULL                 meta-freescale-3rdparty
colibri-imx7-emmc       Toradex Colibri iMX7 Dual 1GB (eMMC)               i.MX 7Dual               meta-freescale-3rdparty
colibri-imx7-nand       Toradex Colibri iMX7D/S (NAND)                     i.MX 7Dual / i.MX 7Solo  meta-freescale-3rdparty
colibri-vf              Toradex Colibri VF50/VF61                          VF500/VF610              meta-freescale-3rdparty
cubox-i                 SolidRun CuBox-i and HummingBoard                  i.MX6 Q/DL               meta-freescale-3rdparty
imx233-olinuxino-maxi   OLIMEX iMX233-OLinuXino-Maxi                       i.MX23                   meta-freescale-3rdparty
imx233-olinuxino-micro  OLIMEX iMX233-OLinuXino-Micro                      i.MX23                   meta-freescale-3rdparty
imx233-olinuxino-mini   OLIMEX iMX233-OLinuXino-Mini                       i.MX23                   meta-freescale-3rdparty
imx233-olinuxino-nano   OLIMEX iMX233-OLinuXino-Nano                       i.MX23                   meta-freescale-3rdparty
imx23evk                NXP i.MX23 Evaluation Kit                          i.MX23                   meta-freescale
imx28evk                NXP i.MX28 Evaluation Kit                          i.MX28                   meta-freescale
imx51evk                NXP i.MX51 Evaluation Kit                          i.MX51                   meta-freescale
imx53qsb                NXP i.MX53 Quick Start Board                       i.MX53                   meta-freescale
imx6dl-riotboard        RIoTboard                                          i.MX6S                   meta-freescale-3rdparty
imx6qdl-pico            IMX6Q/DL-PICO                                      i.MX6QDL                 meta-freescale-3rdparty
imx6qdl-variscite-som   Variscite i.MX6Q/DL VAR-SOM-MX6                    i.MX6Q/DL                meta-freescale-3rdparty
imx6qdlsabreauto        NXP i.MX6QP/Q/DL SABRE Automotive                  i.MX6QP/Q/DL             meta-freescale
imx6qdlsabresd          NXP i.MX6QP/Q/DL SABRE Smart Device                i.MX6QP/Q/DL             meta-freescale
imx6sl-warp             WaRP                                               i.MX6SL                  meta-freescale-3rdparty
imx6slevk               NXP i.MX6SL Evaluation Kit                         i.MX6SL                  meta-freescale
imx6sllevk              NXP i.MX6SLL Evaluation Kit                        i.MX6SLL                 meta-freescale
imx6sxsabreauto         NXP i.MX6SoloX Sabre Automotive                    i.MX6SX                  meta-freescale
imx6sxsabresd           NXP i.MX6SoloX SabreSD                             i.MX6SX                  meta-freescale
imx6ul-kontron          Kontron N63XX/N64XX SoM based boards               i.MX6UL/i.MX6ULL         meta-freescale-3rdparty
imx6ul-pico             IMX6UL-PICO                                        i.MX6UL                  meta-freescale-3rdparty
imx6ulevk               NXP i.MX6UL Evaluation Kit                         i.MX6UL                  meta-freescale
imx6ullevk              NXP i.MX6ULL Evaluation Kit                        i.MX6ULL                 meta-freescale
imx6ulz-14x14-evk       NXP i.MX6ULZ 14x14 Evaluation Kit                  i.MX6ULZ                 meta-freescale
imx7d-pico              IMX7D-PICO                                         i.MX7D                   meta-freescale-3rdparty
imx7d-remarkable2       IMX7D-reMarkable2                                  i.MX7D                   meta-freescale-3rdparty
imx7dsabresd            NXP i.MX7D SABRE Smart Device                      i.MX7D                   meta-freescale
imx7s-warp              WaRP7                                              i.MX7S                   meta-freescale-3rdparty
imx7ulpevk              NXP i.MX7ULP Evaluation Kit                        i.MX7ULP                 meta-freescale
imx8dx-mek              i.MX 8DX MEK                                                                meta-freescale
imx8dxl-ddr3l-evk       i.MX 8DXL EVK with DDR3                                                     meta-freescale
imx8dxl-lpddr4-evk      i.MX 8DXL EVK with LPDDR4                                                   meta-freescale
imx8mm-ddr4-evk         NXP i.MX 8M Mini EVK with DDR4                     i.MX8MM                  meta-freescale
imx8mm-lpddr4-evk       NXP i.MX 8M Mini EVK with LPDDR4                   i.MX8MM                  meta-freescale
imx8mn-ddr4-evk         NXP i.MX 8M Nano Evaluation Kit with DDR4          i.MX8MM                  meta-freescale
imx8mn-lpddr4-evk       NXP i.MX 8M Nano Evaluation Kit with LPDDR4        i.MX8MN                  meta-freescale
imx8mp-ddr4-evk         NXP i.MX 8M Plus EVK with DDR4                     i.MX8MP                  meta-freescale
imx8mp-lpddr4-evk       NXP i.MX 8M Plus EVK with LPDDR4                   i.MX8MP                  meta-freescale
imx8mq-evk              NXP i.MX 8M Quad EVK                               i.MX8MQ                  meta-freescale
imx8qm-mek              i.MX 8QM MEK                                                                meta-freescale
imx8qxp-mek             i.MX 8QXP MEK                                                               meta-freescale
ls1012afrwy             NXP LS1012AFRWY board                              LSCH2                    meta-freescale
ls1012ardb              NXP LS1012ARDB board                               LSCH2                    meta-freescale
ls1021atwr              NXP LS1021ATWR board                               ls102xa                  meta-freescale
ls1028ardb              NXP LS1028ARDB                                     LSCH3                    meta-freescale
ls1043ardb              NXP LS1043ARDB board                               LSCH2                    meta-freescale
ls1046afrwy             NXP LS1046AFRWY                                    LSCH2                    meta-freescale
ls1046ardb              NXP LS1046ARDB                                     LSCH2                    meta-freescale
ls1088ardb              NXP LS1088ARDB                                     LSCH3                    meta-freescale
ls1088ardb-pb           NXP LS1088ARDB                                     LSCH3                    meta-freescale
ls2080ardb              NXP LS2080ARDB board                               LSCH3                    meta-freescale
ls2088ardb              NXP LS2088ARDB                                     LSCH3                    meta-freescale
lx2160acex7             Solid-Run LX2160A-CEx7                             LSCH3                    meta-freescale-3rdparty
lx2160ardb              NXP LX2160ARDB                                     LSCH3                    meta-freescale
lx2162aqds              NXP LX2162AQDS                                     LSCH3                    meta-freescale
mpc8548cds                                                                                          meta-freescale
nitrogen6sx             Boundary Devices Nitrogen6SX                       i.MX6SX                  meta-freescale-3rdparty
nitrogen6x              Boundary Devices Nitrogen6X                        i.MX6 Q/DL               meta-freescale-3rdparty
nitrogen6x-lite         Boundary Devices Nitrogen6X Lite                   i.MX6S                   meta-freescale-3rdparty
nitrogen7               Boundary Devices Nitrogen7                         i.MX7D                   meta-freescale-3rdparty
nitrogen8m              Boundary Devices Nitrogen8M                        i.MX8 MQ                 meta-freescale-3rdparty
nitrogen8mm             Boundary Devices Nitrogen8MM                       i.MX8MM                  meta-freescale-3rdparty
nitrogen8mn             Boundary Devices Nitrogen8M Nano                   i.MX8 Nano               meta-freescale-3rdparty
nitrogen8mp             Boundary Devices Nitrogen8MP                       i.MX8 MP                 meta-freescale-3rdparty
p1020rdb                NXP P1020RDB                                       p1020                    meta-freescale
p2020rdb                                                                   p2020                    meta-freescale
p2041rdb                NXP P2041RDB                                       p2041                    meta-freescale
p3041ds                 NXP P3041DS                                        p3041                    meta-freescale
p4080ds                 NXP P4080DS                                        p4080                    meta-freescale
p5040ds                 NXP P5040DS                                        p5040                    meta-freescale
p5040ds-64b             NXP P5040DS-64B                                    p5040                    meta-freescale
t1024rdb                NXP T1024RDB                                       t1024                    meta-freescale
t1024rdb-64b            NXP T1024RDB                                       t1024                    meta-freescale
t1042d4rdb              NXP T1042D4RDB                                     t1042                    meta-freescale
t1042d4rdb-64b          NXP T1042D4RDB                                     t1042                    meta-freescale
t2080rdb                NXP T2080RDB                                       t2080                    meta-freescale
t2080rdb-64b            NXP T2080RDB                                       t2080                    meta-freescale
t4240rdb                NXP T4240RDB                                       t4240                    meta-freescale
t4240rdb-64b            NXP T4240RDB                                       t4240                    meta-freescale
ventana                 i.MX6Q/DL Ventana Platform                         i.MX6Q/DL                meta-freescale-3rdparty
wandboard               Wandboard i.MX6 Wandboard QuadPlus/Quad/Dual/Solo  i.MX6QP/Q/DL             meta-freescale-3rdparty
======================  =================================================  =======================  =======================
