======================  ==================================================  =======================  =======================
       Machine                                 Name                                   SoC                     Layer
======================  ==================================================  =======================  =======================
apalis-imx6             Toradex Apalis iMX6Q/D                              i.MX6                    meta-freescale-3rdparty
b4420qds                NXP B4420QDS                                        b4420                    meta-freescale
b4420qds-64b            NXP B4420QDS-64B                                    b4420                    meta-freescale
b4860qds                NXP B4860QDS                                        b4860                    meta-freescale
b4860qds-64b            NXP B4860QDS-64B                                    b4860                    meta-freescale
c293pcie                NXP C293PCIE                                        c293pcie                 meta-freescale
cfa10036                Crystalfontz CFA-10036                              i.MX28                   meta-freescale-3rdparty
cfa10037                Crystalfontz CFA-10037                              i.MX28                   meta-freescale-3rdparty
cfa10049                Crystalfontz CFA-10049                              i.MX28                   meta-freescale-3rdparty
cfa10055                Crystalfontz CFA-10055                              i.MX28                   meta-freescale-3rdparty
cfa10056                Crystalfontz CFA-10056                              i.MX28                   meta-freescale-3rdparty
cfa10057                Crystalfontz CFA-10057                              i.MX28                   meta-freescale-3rdparty
cfa10058                Crystalfontz CFA-10058                              i.MX28                   meta-freescale-3rdparty
cgtqmx6                 Congatec QMX6 Evaluation board                      i.MX6 Q/DL               meta-freescale-3rdparty
cm-fx6                  CompuLab CM-FX6                                     i.MX6 Q/DL               meta-freescale-3rdparty
colibri-imx6            Toradex Colibri iMX6DL/S                            i.MX6 DL/S               meta-freescale-3rdparty
colibri-imx7            Toradex Colibri iMX7D/S                             i.MX 7Dual / i.MX 7Solo  meta-freescale-3rdparty
colibri-vf              Toradex Colibri VF50/VF61                           VF500/VF610              meta-freescale-3rdparty
cubox-i                 SolidRun CuBox-i and HummingBoard                   i.MX6 Q/DL               meta-freescale-3rdparty
imx233-olinuxino-maxi   OLIMEX iMX233-OLinuXino-Maxi                        i.MX23                   meta-freescale-3rdparty
imx233-olinuxino-micro  OLIMEX iMX233-OLinuXino-Micro                       i.MX23                   meta-freescale-3rdparty
imx233-olinuxino-mini   OLIMEX iMX233-OLinuXino-Mini                        i.MX23                   meta-freescale-3rdparty
imx233-olinuxino-nano   OLIMEX iMX233-OLinuXino-Nano                        i.MX23                   meta-freescale-3rdparty
imx23evk                NXP i.MX23 Evaluation Kit                           i.MX23                   meta-freescale
imx28evk                NXP i.MX28 Evaluation Kit                           i.MX28                   meta-freescale
imx51evk                NXP i.MX51 Evaluation Kit                           i.MX51                   meta-freescale
imx53ard                NXP i.MX53 SABRE Automotive Board                   i.MX53                   meta-freescale
imx53qsb                NXP i.MX53 Quick Start Board                        i.MX53                   meta-freescale
imx6dl-riotboard        RIoTboard                                           i.MX6S                   meta-freescale-3rdparty
imx6dlsabreauto         NXP i.MX6DL SABRE Automotive                        i.MX6DL                  meta-freescale
imx6dlsabresd           NXP i.MX6DL SABRE Smart Device                      i.MX6DL                  meta-freescale
imx6q-dms-ba16          Advantech DMS BA16                                  i.MX6Q                   meta-freescale-3rdparty
imx6qdl-variscite-som   Variscite i.MX6Q/DL VAR-SOM-MX6                     i.MX6Q/DL                meta-freescale-3rdparty
imx6qpsabreauto         NXP i.MX6Q Plus SABRE Automotive                    i.MX6QP                  meta-freescale
imx6qpsabresd           NXP i.MX6Q Plus SABRE Smart Device                  i.MX6QP                  meta-freescale
imx6qsabreauto          NXP i.MX6Q SABRE Automotive                         i.MX6Q                   meta-freescale
imx6qsabrelite          Boundary Devices i.MX6Q SABRE Lite                  i.MX6Q                   meta-freescale-3rdparty
imx6qsabresd            NXP i.MX6Q SABRE Smart Device                       i.MX6Q                   meta-freescale
imx6sl-warp             WaRP                                                i.MX6SL                  meta-freescale-3rdparty
imx6slevk               NXP i.MX6SL Evaluation Kit                          i.MX6SL                  meta-freescale
imx6solosabreauto       NXP i.MX6Solo SABRE Automotive                      i.MX6S                   meta-freescale
imx6solosabresd         NXP i.MX6Solo SABRE Smart Device                    i.MX6S                   meta-freescale
imx6sxsabreauto         NXP i.MX6SoloX Sabre Automotive                     i.MX6SX                  meta-freescale
imx6sxsabresd           NXP i.MX6SoloX SabreSD                              i.MX6SX                  meta-freescale
imx6ul-pico-hobbit      Hobbitboard (PICO-IMX6UL)                           i.MX6UL                  meta-freescale-3rdparty
imx6ulevk               NXP i.MX6UL Evaluation Kit                          i.MX6UL                  meta-freescale
imx7dsabresd            NXP i.MX7D SABRE Smart Device                       i.MX7D                   meta-freescale
imx7s-warp              WaRP7                                               i.MX7S                   meta-freescale-3rdparty
ls1021atwr              NXP LS1021ATWR board                                ls102xa                  meta-freescale
ls1043ardb              NXP LS1043ARDB board                                LSCH2                    meta-freescale
ls1043ardb-32b          NXP LS1043ARDB-32B                                  LSCH2                    meta-freescale
ls1046ardb              NXP LS1046ARDB                                      LSCH2                    meta-freescale
ls1046ardb-32b          NXP LS1046ARDB                                      LSCH2                    meta-freescale
ls2080ardb              NXP LS2080ARDB board                                LSCH3                    meta-freescale
m28evk                  DENX M28 SoM Evaluation Kit                         i.MX28                   meta-freescale-3rdparty
m53evk                  DENX M53 SoM Evaluation Kit                         i.MX53                   meta-freescale-3rdparty
nitrogen6sx             Boundary Devices Nitrogen6SX                        i.MX6SX                  meta-freescale-3rdparty
nitrogen6x              Boundary Devices Nitrogen6X                         i.MX6 Q/DL               meta-freescale-3rdparty
nitrogen6x-lite         Boundary Devices Nitrogen6X Lite                    i.MX6S                   meta-freescale-3rdparty
nitrogen7               Boundary Devices Nitrogen7                          i.MX7D                   meta-freescale-3rdparty
p2041rdb                NXP P2041RDB                                        p2041                    meta-freescale
p3041ds                 NXP P3041DS                                         p3041                    meta-freescale
p4080ds                 NXP P4080DS                                         p4080                    meta-freescale
p5020ds                 NXP P5020DS                                         p5020                    meta-freescale
p5020ds-64b             NXP P5020DS-64B                                     p5020                    meta-freescale
p5040ds                 NXP P5040DS                                         p5040                    meta-freescale
p5040ds-64b             NXP P5040DS-64B                                     p5040                    meta-freescale
pcm052                  Phytec phyCORE Vybrid Development Kit               vf60                     meta-freescale-3rdparty
t1023rdb                NXP T1023RDB                                        t1023                    meta-freescale
t1023rdb-64b            NXP T1023RDB                                        t1023                    meta-freescale
t1024rdb                NXP T1024RDB                                        t1024                    meta-freescale
t1024rdb-64b            NXP T1024RDB                                        t1024                    meta-freescale
t1040d4rdb              NXP T1040D4RDB                                      t1040                    meta-freescale
t1040d4rdb-64b          NXP T1040D4RDB                                      t1040                    meta-freescale
t1042d4rdb              NXP T1042D4RDB                                      t1042                    meta-freescale
t1042d4rdb-64b          NXP T1042D4RDB                                      t1042                    meta-freescale
t2080qds                NXP T2080QDS                                        t2080                    meta-freescale
t2080qds-64b            NXP T2080QDS-64B                                    t2080                    meta-freescale
t2080rdb                NXP T2080RDB                                        t2080                    meta-freescale
t2080rdb-64b            NXP T2080RDB                                        t2080                    meta-freescale
t4160qds                NXP T4160QDS                                        t4160                    meta-freescale
t4160qds-64b            NXP T4160QDS-64B                                    t4160                    meta-freescale
t4240qds                NXP T4240QDS                                        t4240                    meta-freescale
t4240qds-64b            NXP T4240QDS-64B                                    t4240                    meta-freescale
t4240rdb                NXP T4240RDB                                        t4240                    meta-freescale
t4240rdb-64b            NXP T4240RDB                                        t4240                    meta-freescale
twr-vf65gs10            NXP Vybrid TWR-VF65GS10                             VF610                    meta-freescale
tx6q-10x0               Ka-Ro electronics i.MX6Q TX6Q Computer-On-Module    i.MX6Q                   meta-freescale-3rdparty
tx6q-11x0               Ka-Ro electronics i.MX6Q TX6Q Computer-On-Module    i.MX6Q                   meta-freescale-3rdparty
tx6s-8034               Ka-Ro electronics i.MX6S TX6S Computer-On-Module    i.MX6S                   meta-freescale-3rdparty
tx6s-8035               Ka-Ro electronics i.MX6S TX6S Computer-On-Module    i.MX6S                   meta-freescale-3rdparty
tx6u-8033               Ka-Ro electronics i.MX6DL TX6DL Computer-On-Module  i.MX6DL                  meta-freescale-3rdparty
tx6u-80x0               Ka-Ro electronics i.MX6DL TX6DL Computer-On-Module  i.MX6DL                  meta-freescale-3rdparty
tx6u-81x0               Ka-Ro electronics i.MX6DL TX6DL Computer-On-Module  i.MX6DL                  meta-freescale-3rdparty
ventana                 i.MX6Q/DL Ventana Platform                          i.MX6Q/DL                meta-freescale-3rdparty
wandboard               Wandboard i.MX6 Wandboard Quad/Dual/Solo            i.MX6Q/DL                meta-freescale-3rdparty
======================  ==================================================  =======================  =======================
