======  ==================  ================================================================================
Bug ID        Status                                            Summary
======  ==================  ================================================================================
11881   NEW                 add infrastructure to allow BSPs to switch between *set* of configurations
13251   IN PROGRESS DESIGN  Symlinks overridden when building multitple kernels
13938   ACCEPTED            devtool modify virtual/kernel fails when EXTRAVERSION field is empty in Makefile
6428    IN PROGRESS DESIGN  Improve the ability to isolate changes that have caused a rebuild
======  ==================  ================================================================================
