======  ==================  ========================================================================================================
Bug ID        Status                                                        Summary
======  ==================  ========================================================================================================
11125   NEW                 freescale GPU driver imx-gpu-viv is incompatible with kernel linux-fscl
11881   NEW                 add infrastructure to allow BSPs to switch between *set* of configurations
12151   NEW                 Packages tslib-conf, tslib-tests and tslib-calibrate do not get installed in root filesystem without X11
6428    IN PROGRESS DESIGN  Improve the ability to isolate changes that have caused a rebuild
======  ==================  ========================================================================================================
