* **packagegroup-fsl-gstreamer**: Package group used by FSL Community to provide audio, video, and debug GStreamer's plugins with the required hardware acceleration (if supported by the SoC).
* **packagegroup-fsl-gstreamer-full**: Package group used by FSL Community to provide audio, video, and debug GStreamer's plugins (including good and bad ones) with the required hardware acceleration (if supported by the SoC).
* **packagegroup-fsl-mfgtool**: Freescale Manufacturing Tool requirements.
* **packagegroup-fsl-tools-benchmark**: Package group used by FSL Community to provide a set of benchmark applications.
* **packagegroup-fsl-tools-gpu**: Package group used by FSL Community to add the packages which provide GPU support.
* **packagegroup-fsl-tools-gpu-external**: Package group used by FSL Community to provide graphic packages used to test the several hardware accelerated graphics APIs including packages not provided by Freescale.
* **packagegroup-fsl-tools-testapps**: Packagegroup used by FSL Community to provide a set of packages and utilities for hardware test.
* **packagegroup-fslc-gstreamer1.0**: Package group used by FSL Community to provide audio, video, networking and debug GStreamer plugins with the required hardware acceleration (if supported by the SoC).
* **packagegroup-fslc-gstreamer1.0-full**: Package group used by FSL Community to provide all GStreamer plugins from the base, good, and bad packages, as well as the ugly and libav ones if commercial packages are whitelisted, and plugins for the required hardware acceleration (if supported by the SoC).
