* **packagegroup-fsl-gstreamer**: Freescale's package group which provides audio, video, and debug gstreamer's plugins with the required hardware acceleration (if supported by the SoC).
* **packagegroup-fsl-gstreamer-full**: Freescale's package group which provides audio, video, and debug gstreamer's plugins (including good and bad ones) with the required hardware acceleration (if supported by the SoC).
* **packagegroup-fsl-mfgtool**: Freescale Manufacturing Tool requirements.
* **packagegroup-fsl-tools-benchmark**: Freescale's package group which provides a set of benchmark applications.
* **packagegroup-fsl-tools-gpu**: Freescale's package group used to add the packages which provides GPU support.
* **packagegroup-fsl-tools-gpu-external**: Freescale's package group which provides graphic packages used to test the several hardware accelerated graphics APIs including packages not provided by Freescale.
* **packagegroup-fsl-tools-testapps**: Freescale's package group provides a set of packages and utilities for hardware test.
* **packagegroup-fslc-gstreamer1.0**: Freescale package group which provides audio, video, networking and debug  GStreamer plugins with the required hardware acceleration (if supported by the SoC).
* **packagegroup-fslc-gstreamer1.0-full**: Freescale package group which provides all GStreamer plugins from the  base, good, and bad packages, as well as the ugly and libav ones if commercial packages  are whitelisted, and plugins for the required hardware acceleration (if supported by the SoC).
