========================   =============   =============   =============   ======
Package Name                mx28           mx5             mx6             vf60
========================   =============   =============   =============   ======
imx-test                   3.10.17-1.0.0   3.10.17-1.0.0   3.10.17-1.0.0   -
gst-fsl-plugin             3.0.10          3.0.10          3.0.10          -
libfslcodec                3.0.10          3.0.10          3.0.10          -
libfslparser               3.0.10          3.0.10          3.0.10          -
imx-vpu                    -               11.09.02        3.10.17-1.0.0   -
imx-lib                    -               11.09.02        3.10.17-1.0.0   -
firmware-imx               -               3.0.35-4.0.0    3.0.35-4.0.0    -
mxsldr                     git             -               -               -
gpu-viv-g2d                -               -                               -
xf86-video-imxfb-vivante   -               -               3.10.17-1.0.0   -
gpu-viv-bin-mx6q           -               -               3.10.17-1.0.0   -
directfb                   -               -               1.6.3           -
directfb-examples          -               -               1.6.0           -
xf86-video-imxfb           -               11.09.02        -               -
amd-gpu-bin-mx51           -               11.09.02        -               -
libz160                    -               11.09.02        -               -
amd-gpu-x11-bin-mx51       -               11.09.02        -               -
libfslvpuwrap              -               -               1.0.45 [1]      -
fsl-alsa-plugins           -               -               1.0.25          -
gstreamer1.0-plugins-imx   -               -               0.9.5           -
imx-uuc                                                                    -
libmcc                     -               -               -
mqxboot                    -               -               -               1.0
========================   =============   =============   =============   ======

