========================   =============   ========================    ==========================  ======
Package Name                mx28           mx5                         mx6                         vf60
========================   =============   ========================    ==========================  ======
imx-test                   3.10.17-1.0.0   |latest_bsp_version_mx6|    |latest_bsp_version_mx6|    -
gst-fsl-plugin             |mm_version|    |mm_version|                |mm_version|                -
libfslcodec                |mm_version|    |mm_version|                |mm_version|                -
libfslparser               |mm_version|    |mm_version|                |mm_version|                -
imx-vpu                    -               11.09.02                    |latest_bsp_version_mx6|    -
imx-lib                    -               11.09.02                    |latest_bsp_version_mx6|    -
firmware-imx               -               |latest_bsp_version_mx6|    |latest_bsp_version_mx6|    -
mxsldr                     git             -                           -                           -
gpu-viv-g2d                -               -                           |latest_bsp_version_mx6|    -
xf86-video-imxfb-vivante   -               -                           |latest_bsp_version_mx6|    -
gpu-viv-bin-mx6q           -               -                           |latest_bsp_version_mx6|    -
directfb                   -               -                           1.6.3                       -
directfb-examples          -               -                           1.6.0                       -
xf86-video-imxfb           -               |latest_bsp_version_mx5|    -                           -
amd-gpu-bin-mx51           -               |latest_bsp_version_mx5|    -                           -
libz160                    -               |latest_bsp_version_mx5|    -                           -
amd-gpu-x11-bin-mx51       -               |latest_bsp_version_mx5|    -                           -
libfslvpuwrap              -               -                           |libfslvpuwrap_version|[1]  -
fsl-alsa-plugins           -               -                           1.0.25                      -
gstreamer1.0-plugins-imx   -               -                           0.9.5                       -
imx-uuc                                                                                            -
libmcc                     -               -                           -
mqxboot                    -               -                           -                           1.0
========================   =============   ========================    ==========================  ======

