========================   ===============   ===============   ===============   ======
Package Name                mx28             mx5               mx6               vf60
========================   ===============   ===============   ===============   ======
imx-test                   HW-specific       HW-specific       HW-specific       --
gst-fsl-plugin             HW-specific       HW-specific       HW-specific       --
libfslcodec                HW optimization   HW acceleration   HW acceleration   --
libfslparser               HW optimization   HW optimization   HW optimization   --
imx-vpu                    --                HW acceleration   HW acceleration   --
imx-lib                    --                HW acceleration   HW acceleration   --
firmware-imx               --                HW-specific       HW-specific       --
mxsldr                     HW-specific       --                --                --
gpu-viv-g2d                --                --                HW acceleration   --
xf86-video-imxfb-vivante   --                --                HW acceleration   --
gpu-viv-bin-mx6q           --                --                HW acceleration   --
directfb                   --                --                HW acceleration   --
directfb-examples          --                --                HW acceleration   --
xf86-video-imxfb           --                HW acceleration   --                --
amd-gpu-bin-mx51           --                HW acceleration   --                --
libz160                    --                HW acceleration   --                --
amd-gpu-x11-bin-mx51       --                HW acceleration   --                --
libfslvpuwrap              --                --                HW acceleration   --
fsl-alsa-plugins           --                --                HW-specific       --
gstreamer1.0-plugins-imx   --                --                HW acceleration   --
imx-uuc                    HW-specific       HW-specific       HW-specific       --
libmcc                     --                --                --
mqxboot                    --                --                --                HW-specific
========================   ===============   ===============   ===============   ======
