----------------------------------------------
Freescale i.MX6DL SABRE Smart Device (i.MX6DL)
----------------------------------------------

This board was tested by 2 persons.

2 images were used:

  * fsl-image-test
  * core-image-minimal


--------------------------------------------
Freescale i.MX6Q SABRE Smart Device (i.MX6Q)
--------------------------------------------

This board was tested by 2 persons.

3 images were used:

  * core-image-x11
  * core-image-base
  * core-image-directfb


-------------------------------------------
Boundary Devices i.MX6Q SABRE Lite (i.MX6Q)
-------------------------------------------

This board was tested by 1 person.

1 image was used:

  * fsl-image-gui


--------------------------------------------
Wandboard i.MX6 Wandboard Duallite (i.MX6DL)
--------------------------------------------

This board was tested by 1 person.

2 images were used:

  * core-image-x11
  * core-image-directfb


-------------------------------------------
Freescale i.MX53 Quick Start Board (i.MX53)
-------------------------------------------

This board was tested by 1 person.

1 image was used:

  * fsl-image-test


-------------------------------
Crystalfontz CFA-10036 (i.MX28)
-------------------------------

This board was tested by 1 person.

1 image was used:

  * core-image-minimal


-------------------------------
Crystalfontz CFA-10037 (i.MX28)
-------------------------------

This board was tested by 1 person.

1 image was used:

  * core-image-minimal


------------------------------------------------
Freescale i.MX53 SABRE Automotive Board (i.MX53)
------------------------------------------------

This board was tested by 1 person.

1 image was used:

  * fsl-image-test


----------------------------------------
Freescale i.MX28 Evaluation Kit (i.MX28)
----------------------------------------

This board was tested by 1 person.

2 images were used:

  * core-image-base
  * fsl-image-test


=================
Not tested boards
=================

The following boards have not been tested:

  * Freescale i.MX6Solo SABRE Automotive (i.MX6S)
  * Congatec Qmx6 (i.MX6Q)
  * Freescale i.MX51 Evaluation Kit (i.MX51)
  * Boundary Devices Nitrogen6X Lite (i.MX6 Solo)
  * Freescale i.MX6SL Evaluation Kit (i.MX6SL)
  * Freescale i.MX35 Platform Development Kit (i.MX35)
  * DENX M53 SoM Evaluation Kit (i.MX53)
  * Crystalfontz CFA-10049 (i.MX28)
  * OLIMEX iMX233-OLinuXino-Maxi (i.MX23)
  * OLIMEX iMX233-OLinuXino-Mini (i.MX23)
  * Freescale i.MX23 Evaluation Kit (i.MX23)
  * Boundary Devices Nitrogen6X (i.MX6Q)
  * Freescale i.MX6DL SABRE Automotive (i.MX6DL)
  * DENX M28 SoM Evaluation Kit (i.MX28)
  * Freescale i.MX31 Platform Development Kit (i.MX31)
  * Wandboard i.MX6 Wandboard Quad (i.MX6Q)
  * Freescale i.MX6Solo SABRE Smart Device (i.MX6S)
  * Crystalfontz CFA-10058 (i.MX28)
  * Crystalfontz CFA-10056 (i.MX28)
  * Crystalfontz CFA-10057 (i.MX28)
  * Crystalfontz CFA-10055 (i.MX28)
  * Freescale Vybrid TWR-VF65GS10 (vf60)
  * Wandboard i.MX6 Wandboard Solo (i.MX6S)
  * OLIMEX iMX233-OLinuXino-Micro (i.MX23)
  * Freescale i.MX6Q SABRE Automotive (i.MX6Q)
