======================  =========  ===================
Board                   SFP        memtester overnight
======================  =========  ===================
imx6qsabrelite          |na_mark|  |check_mark|
nitrogen6x
nitrogen6x-lite
cgtqmx6
cfa10036
cfa10037
cfa10049
cfa10055
cfa10056
cfa10057
cfa10058
m28evk
m53evk
imx23evk
imx28evk                |na_mark|  |check_mark|
imx31pdk
imx35pdk
imx51evk
imx53qsb                           |check_mark|
imx53ard                           |check_mark|
imx6dlsabreauto
imx6dlsabresd
imx6qsabreauto
imx6qsabresd                       |check_mark|
imx6slevk
imx6solosabreauto
imx6solosabresd
twr-vf65gs10
imx233-olinuxino-maxi
imx233-olinuxino-micro
imx233-olinuxino-mini
wandboard-dual
wandboard-quad
wandboard-solo
======================  =========  ===================
