======================  ================  ============  =================  ===============  ==================  =================  =============== ============
Board                   Play one movie    Play mp3      Encode one movie   Functional USB   Functional SDCard   Functional aplay   memtester 50M   DirectFB
======================  ================  ============  =================  ===============  ==================  =================  =============== ============
imx6qsabrelite          |na_mark|         |check_mark|  |na_mark|          |check_mark|     |check_mark|        |check_mark|       |check_mark|    |check_mark|
nitrogen6x
nitrogen6x-lite
cgtqmx6
cfa10036                                                                   |na_mark|        |check_mark|        |na_mark|          |check_mark|    |na_mark|
cfa10037                                                                   |check_mark|     |check_mark|                           |check_mark|    |na_mark|
cfa10049                                                                   |check_mark|     |check_mark|        |na_mark|          |check_mark|    |na_mark|
cfa10055                                                                   |check_mark|     |check_mark|        |na_mark|          |check_mark|    |na_mark|
cfa10056                                                                   |check_mark|     |check_mark|        |na_mark|          |check_mark|    |na_mark|
cfa10057                                                                   |check_mark|     |check_mark|                           |check_mark|    |na_mark|
cfa10058                                                                   |check_mark|     |check_mark|        |na_mark|          |check_mark|    |na_mark|
m28evk
m53evk
imx23evk
imx28evk                |check_mark|                    |na_mark|          |check_mark|     |na_mark|           |check_mark|       |na_mark|       |na_mark|
imx31pdk
imx35pdk
imx51evk
imx53qsb                |check_mark|      |check_mark|  |x_mark|                                                                   |check_mark|
imx53ard                |check_mark|                                       |x_mark|         |na_mark|           |check_mark|       |check_mark|
imx6dlsabreauto
imx6dlsabresd           |check_mark|      |check_mark|                                                                             |check_mark|
imx6qsabreauto
imx6qsabresd            |check_mark|                                       |check_mark|     |check_mark|        |check_mark|       |check_mark|    |check_mark|
imx6slevk
imx6solosabreauto
imx6solosabresd
twr-vf65gs10
imx233-olinuxino-maxi
imx233-olinuxino-micro
imx233-olinuxino-mini
wandboard-dual                                                             |check_mark|     |check_mark|        |check_mark|       |check_mark|
wandboard-quad
wandboard-solo
======================  ================  ============  =================  ===============  ==================  =================  =============== ============
