======================  =======================   ====================  =======================
Board                   Reach Userspace Prompt    Alive during tests    Accelerated and up X11 
======================  =======================   ====================  =======================
imx6qsabrelite          Y                         Y                     Y
nitrogen6x
nitrogen6x-lite
cgtqmx6
cfa10036                Y                         Y                     `-`
cfa10037                Y                         Y                     `-`
cfa10049                Y                         Y                     Y
cfa10055                Y                         Y                     `-`
cfa10056                Y                         Y                     Y
cfa10057                Y                         Y                     Y
cfa10058                Y                         Y                     Y
m28evk
m53evk
imx23evk
imx28evk                Y                         Y                     `-`
imx31pdk
imx35pdk
imx51evk
imx53qsb                Y                         Y
imx53ard                Y                         Y
imx6dlsabreauto
imx6dlsabresd           Y                         Y
imx6qsabreauto
imx6qsabresd            Y                         Y
imx6slevk
imx6solosabreauto
imx6solosabresd
twr-vf65gs10
imx233-olinuxino-maxi
imx233-olinuxino-micro
imx233-olinuxino-mini
wandboard-dual          Y                         Y                     Y
wandboard-quad
wandboard-solo
======================  =======================   ====================  =======================
