==================      ========================      =================================
Board                   u-boot Version                FSL BSP
==================      ========================      =================================
imx28evk                |u_boot_imx_version_mxs|      |u_boot_imx_tag_mxs|
imx51evk                |u_boot_imx_version_mx5|      |u_boot_imx_tag_mx5|
imx53qsb                |u_boot_imx_version_mx5|      |u_boot_imx_tag_mx5|
imx53ard                |u_boot_imx_version_mx5|      |u_boot_imx_tag_mx5|
imx6slevk               |u_boot_imx_version_mx6|      |u_boot_imx_tag_mx6|
imx6solosabreauto       |u_boot_imx_version_mx6|      |u_boot_imx_tag_mx6|
imx6solosabresd         |u_boot_imx_version_mx6|      |u_boot_imx_tag_mx6|
imx6dlsabreauto         |u_boot_imx_version_mx6|      |u_boot_imx_tag_mx6|
imx6dlsabresd           |u_boot_imx_version_mx6|      |u_boot_imx_tag_mx6|
imx6qsabreauto          |u_boot_imx_version_mx6|      |u_boot_imx_tag_mx6|
imx6qsabresd            |u_boot_imx_version_mx6|      |u_boot_imx_tag_mx6|
==================      ========================      =================================

