* **fslc-framebuffer**: Distro for Framebuffer graphical backend. This distro doesn't include x11 and wayland features.
* **fslc-wayland**: Distro for Wayland without X11. This distro include wayland feature but doesn't has x11 support.
* **fslc-x11**: Distro for X11 without wayland. This distro include x11 feature and doesn' has wayland support.
* **fslc-xwayland**: Distro for Wayland with X11. This distro include both wayland and x11 features.
