* **fsl-image-machine-test**: A console-only image that includes gstreamer packages, Freescale's multimedia packages (VPU and GPU) when available, and test and benchmark applications.
* **fsl-image-mfgtool-initramfs**: Small image to be used with Manufacturing Tool (mfg-tool) in a production environment.
* **fsl-image-multimedia**: A console-only image that includes gstreamer packages and Freescale's multimedia packages (VPU and GPU) when available for the specific machine.
* **fsl-image-multimedia-full**: A console-only image that includes gstreamer packages and Freescale's multimedia packages (VPU and GPU) when available for the specific machine.
* **qt-in-use-image**: qt-in-use-image version 1.0-r0.
* **qte-in-use-image**: qte-in-use-image version 1.0-r0.
